import { ActionHandler, State } from '../interfaces/State'
import { StateType } from '../interfaces/StateType'
import { A_WeaponReady, A_FirePistol, A_Light0, A_Light1, A_Lower, A_Raise, A_ReFire } from './actions'
import {
    A_Punch,
    A_FireShotgun,
    A_Light2,
    A_FireShotgun2,
    A_CheckReload,
    A_OpenShotgun2,
    A_LoadShotgun2,
    A_CloseShotgun2,
    A_FireCGun,
    A_GunFlash,
    A_FireMissile,
    A_Saw,
    A_FirePlasma,
    A_BFGsound,
    A_FireBFG,
    A_BFGSpray,
    A_Explode,
    A_Pain,
    A_PlayerScream,
    A_Fall,
    A_XScream,
    A_Look,
    A_Chase,
    A_FaceTarget,
    A_PosAttack,
    A_Scream,
    A_SPosAttack,
    A_VileChase,
    A_VileStart,
    A_VileTarget,
    A_VileAttack,
    A_StartFire,
    A_Fire,
    A_FireCrackle,
    A_Tracer,
    A_SkelWhoosh,
    A_SkelFist,
    A_SkelMissile,
    A_FatRaise,
    A_FatAttack1,
    A_FatAttack2,
    A_FatAttack3,
    A_BossDeath,
    A_CPosAttack,
    A_CPosRefire,
    A_TroopAttack,
    A_SargAttack,
    A_HeadAttack,
    A_BruisAttack,
    A_SkullAttack,
    A_Metal,
    A_SpidRefire,
    A_BabyMetal,
    A_BspiAttack,
    A_Hoof,
    A_CyberAttack,
    A_PainAttack,
    A_PainDie,
    A_KeenDie,
    A_BrainPain,
    A_BrainScream,
    A_BrainDie,
    A_BrainAwake,
    A_BrainSpit,
    A_SpawnSound,
    A_SpawnFly,
    A_BrainExplode
} from './StubDeclarations'

export type StateLookupType = { [type in StateType]: State }

const s = (
    spriteName: string,
    frame: number,
    tics: number,
    action: ActionHandler | undefined,
    nextState: StateType,
    spriteOffsetX?: number
): State => ({
    spriteName,
    frame,
    tics,
    action,
    nextState,
    spriteOffsetX
})

// Build using info.c from original doom source and the following regex substitution:
// \{SPR_([A-Z0-9]{4}),([0-9]+),([\-0-9]+),\{(NULL|A_[A-Za-z0-9]+)\},(S_[_A-Z0-9]+)[0-9,]+\}[,]*[\s]*\/\/\s(S_[A-Z0-9_]+)
// [StateType.$6]: s('$1', $2, $3, $4, StateType.$5),
// Then lower case -> Ctrl+F '[A-Z0-9]{4}' Ctrl+Shift+L Ctrl+Shift+P Transform to lower case
// Then replace NULL -> Ctrl+H , undefined, with , undefined,

export const StateLookup: StateLookupType = {
    [StateType.S_NULL]: s('troo', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_LIGHTDONE]: s('shtg', 4, 0, A_Light0, StateType.S_NULL),
    [StateType.S_PUNCH]: s('pung', 0, 1, A_WeaponReady, StateType.S_PUNCH, 36),
    [StateType.S_PUNCHDOWN]: s('pung', 0, 1, A_Lower, StateType.S_PUNCHDOWN, 36),
    [StateType.S_PUNCHUP]: s('pung', 0, 1, A_Raise, StateType.S_PUNCHUP, 36),
    [StateType.S_PUNCH1]: s('pung', 1, 4, undefined, StateType.S_PUNCH2, -53),
    [StateType.S_PUNCH2]: s('pung', 2, 4, A_Punch, StateType.S_PUNCH3, -55),
    [StateType.S_PUNCH3]: s('pung', 3, 5, undefined, StateType.S_PUNCH4, -46),
    [StateType.S_PUNCH4]: s('pung', 2, 4, undefined, StateType.S_PUNCH5, -55),
    [StateType.S_PUNCH5]: s('pung', 1, 5, A_ReFire, StateType.S_PUNCH, -53),
    [StateType.S_PISTOL]: s('pisg', 0, 1, A_WeaponReady, StateType.S_PISTOL, -5),
    [StateType.S_PISTOLDOWN]: s('pisg', 0, 1, A_Lower, StateType.S_PISTOLDOWN, -5),
    [StateType.S_PISTOLUP]: s('pisg', 0, 1, A_Raise, StateType.S_PISTOLUP, -5),
    [StateType.S_PISTOL1]: s('pisg', 0, 4, undefined, StateType.S_PISTOL2, -5),
    [StateType.S_PISTOL2]: s('pisg', 1, 6, A_FirePistol, StateType.S_PISTOL3, -16),
    [StateType.S_PISTOL3]: s('pisg', 2, 4, undefined, StateType.S_PISTOL4, -7),
    [StateType.S_PISTOL4]: s('pisg', 1, 5, A_ReFire, StateType.S_PISTOL, -16),
    [StateType.S_PISTOLFLASH]: s('pisf', 32768, 7, A_Light1, StateType.S_LIGHTDONE),
    [StateType.S_SGUN]: s('shtg', 0, 1, A_WeaponReady, StateType.S_SGUN),
    [StateType.S_SGUNDOWN]: s('shtg', 0, 1, A_Lower, StateType.S_SGUNDOWN),
    [StateType.S_SGUNUP]: s('shtg', 0, 1, A_Raise, StateType.S_SGUNUP),
    [StateType.S_SGUN1]: s('shtg', 0, 3, undefined, StateType.S_SGUN2),
    [StateType.S_SGUN2]: s('shtg', 0, 7, A_FireShotgun, StateType.S_SGUN3),
    [StateType.S_SGUN3]: s('shtg', 1, 5, undefined, StateType.S_SGUN4, -58),
    [StateType.S_SGUN4]: s('shtg', 2, 5, undefined, StateType.S_SGUN5, -71),
    [StateType.S_SGUN5]: s('shtg', 3, 4, undefined, StateType.S_SGUN6, -74),
    [StateType.S_SGUN6]: s('shtg', 2, 5, undefined, StateType.S_SGUN7, -71),
    [StateType.S_SGUN7]: s('shtg', 1, 5, undefined, StateType.S_SGUN8, -58),
    [StateType.S_SGUN8]: s('shtg', 0, 3, undefined, StateType.S_SGUN9),
    [StateType.S_SGUN9]: s('shtg', 0, 7, A_ReFire, StateType.S_SGUN),
    [StateType.S_SGUNFLASH1]: s('shtf', 32768, 4, A_Light1, StateType.S_SGUNFLASH2),
    [StateType.S_SGUNFLASH2]: s('shtf', 32769, 3, A_Light2, StateType.S_LIGHTDONE),
    [StateType.S_DSGUN]: s('sht2', 0, 1, A_WeaponReady, StateType.S_DSGUN),
    [StateType.S_DSGUNDOWN]: s('sht2', 0, 1, A_Lower, StateType.S_DSGUNDOWN),
    [StateType.S_DSGUNUP]: s('sht2', 0, 1, A_Raise, StateType.S_DSGUNUP),
    [StateType.S_DSGUN1]: s('sht2', 0, 3, undefined, StateType.S_DSGUN2),
    [StateType.S_DSGUN2]: s('sht2', 0, 7, A_FireShotgun2, StateType.S_DSGUN3),
    [StateType.S_DSGUN3]: s('sht2', 1, 7, undefined, StateType.S_DSGUN4),
    [StateType.S_DSGUN4]: s('sht2', 2, 7, A_CheckReload, StateType.S_DSGUN5),
    [StateType.S_DSGUN5]: s('sht2', 3, 7, A_OpenShotgun2, StateType.S_DSGUN6),
    [StateType.S_DSGUN6]: s('sht2', 4, 7, undefined, StateType.S_DSGUN7),
    [StateType.S_DSGUN7]: s('sht2', 5, 7, A_LoadShotgun2, StateType.S_DSGUN8),
    [StateType.S_DSGUN8]: s('sht2', 6, 6, undefined, StateType.S_DSGUN9),
    [StateType.S_DSGUN9]: s('sht2', 7, 6, A_CloseShotgun2, StateType.S_DSGUN10),
    [StateType.S_DSGUN10]: s('sht2', 0, 5, A_ReFire, StateType.S_DSGUN),
    [StateType.S_DSNR1]: s('sht2', 1, 7, undefined, StateType.S_DSNR2),
    [StateType.S_DSNR2]: s('sht2', 0, 3, undefined, StateType.S_DSGUNDOWN),
    [StateType.S_DSGUNFLASH1]: s('sht2', 32776, 5, A_Light1, StateType.S_DSGUNFLASH2),
    [StateType.S_DSGUNFLASH2]: s('sht2', 32777, 4, A_Light2, StateType.S_LIGHTDONE),
    [StateType.S_CHAIN]: s('chgg', 0, 1, A_WeaponReady, StateType.S_CHAIN),
    [StateType.S_CHAINDOWN]: s('chgg', 0, 1, A_Lower, StateType.S_CHAINDOWN),
    [StateType.S_CHAINUP]: s('chgg', 0, 1, A_Raise, StateType.S_CHAINUP),
    [StateType.S_CHAIN1]: s('chgg', 0, 4, A_FireCGun, StateType.S_CHAIN2),
    [StateType.S_CHAIN2]: s('chgg', 1, 4, A_FireCGun, StateType.S_CHAIN3),
    [StateType.S_CHAIN3]: s('chgg', 1, 0, A_ReFire, StateType.S_CHAIN),
    [StateType.S_CHAINFLASH1]: s('chgf', 32768, 5, A_Light1, StateType.S_LIGHTDONE),
    [StateType.S_CHAINFLASH2]: s('chgf', 32769, 5, A_Light2, StateType.S_LIGHTDONE),
    [StateType.S_MISSILE]: s('misg', 0, 1, A_WeaponReady, StateType.S_MISSILE),
    [StateType.S_MISSILEDOWN]: s('misg', 0, 1, A_Lower, StateType.S_MISSILEDOWN),
    [StateType.S_MISSILEUP]: s('misg', 0, 1, A_Raise, StateType.S_MISSILEUP),
    [StateType.S_MISSILE1]: s('misg', 1, 8, A_GunFlash, StateType.S_MISSILE2),
    [StateType.S_MISSILE2]: s('misg', 1, 12, A_FireMissile, StateType.S_MISSILE3),
    [StateType.S_MISSILE3]: s('misg', 1, 0, A_ReFire, StateType.S_MISSILE),
    [StateType.S_MISSILEFLASH1]: s('misf', 32768, 3, A_Light1, StateType.S_MISSILEFLASH2),
    [StateType.S_MISSILEFLASH2]: s('misf', 32769, 4, undefined, StateType.S_MISSILEFLASH3),
    [StateType.S_MISSILEFLASH3]: s('misf', 32770, 4, A_Light2, StateType.S_MISSILEFLASH4),
    [StateType.S_MISSILEFLASH4]: s('misf', 32771, 4, A_Light2, StateType.S_LIGHTDONE),
    [StateType.S_SAW]: s('sawg', 2, 4, A_WeaponReady, StateType.S_SAWB),
    [StateType.S_SAWB]: s('sawg', 3, 4, A_WeaponReady, StateType.S_SAW),
    [StateType.S_SAWDOWN]: s('sawg', 2, 1, A_Lower, StateType.S_SAWDOWN),
    [StateType.S_SAWUP]: s('sawg', 2, 1, A_Raise, StateType.S_SAWUP),
    [StateType.S_SAW1]: s('sawg', 0, 4, A_Saw, StateType.S_SAW2),
    [StateType.S_SAW2]: s('sawg', 1, 4, A_Saw, StateType.S_SAW3),
    [StateType.S_SAW3]: s('sawg', 1, 0, A_ReFire, StateType.S_SAW),
    [StateType.S_PLASMA]: s('plsg', 0, 1, A_WeaponReady, StateType.S_PLASMA),
    [StateType.S_PLASMADOWN]: s('plsg', 0, 1, A_Lower, StateType.S_PLASMADOWN),
    [StateType.S_PLASMAUP]: s('plsg', 0, 1, A_Raise, StateType.S_PLASMAUP),
    [StateType.S_PLASMA1]: s('plsg', 0, 3, A_FirePlasma, StateType.S_PLASMA2),
    [StateType.S_PLASMA2]: s('plsg', 1, 20, A_ReFire, StateType.S_PLASMA),
    [StateType.S_PLASMAFLASH1]: s('plsf', 32768, 4, A_Light1, StateType.S_LIGHTDONE),
    [StateType.S_PLASMAFLASH2]: s('plsf', 32769, 4, A_Light1, StateType.S_LIGHTDONE),
    [StateType.S_BFG]: s('bfgg', 0, 1, A_WeaponReady, StateType.S_BFG),
    [StateType.S_BFGDOWN]: s('bfgg', 0, 1, A_Lower, StateType.S_BFGDOWN),
    [StateType.S_BFGUP]: s('bfgg', 0, 1, A_Raise, StateType.S_BFGUP),
    [StateType.S_BFG1]: s('bfgg', 0, 20, A_BFGsound, StateType.S_BFG2),
    [StateType.S_BFG2]: s('bfgg', 1, 10, A_GunFlash, StateType.S_BFG3),
    [StateType.S_BFG3]: s('bfgg', 1, 10, A_FireBFG, StateType.S_BFG4),
    [StateType.S_BFG4]: s('bfgg', 1, 20, A_ReFire, StateType.S_BFG),
    [StateType.S_BFGFLASH1]: s('bfgf', 32768, 11, A_Light1, StateType.S_BFGFLASH2),
    [StateType.S_BFGFLASH2]: s('bfgf', 32769, 6, A_Light2, StateType.S_LIGHTDONE),
    [StateType.S_BLOOD1]: s('blud', 2, 8, undefined, StateType.S_BLOOD2),
    [StateType.S_BLOOD2]: s('blud', 1, 8, undefined, StateType.S_BLOOD3),
    [StateType.S_BLOOD3]: s('blud', 0, 8, undefined, StateType.S_NULL),
    [StateType.S_PUFF1]: s('puff', 32768, 4, undefined, StateType.S_PUFF2),
    [StateType.S_PUFF2]: s('puff', 1, 4, undefined, StateType.S_PUFF3),
    [StateType.S_PUFF3]: s('puff', 2, 4, undefined, StateType.S_PUFF4),
    [StateType.S_PUFF4]: s('puff', 3, 4, undefined, StateType.S_NULL),
    [StateType.S_TBALL1]: s('bal1', 32768, 4, undefined, StateType.S_TBALL2),
    [StateType.S_TBALL2]: s('bal1', 32769, 4, undefined, StateType.S_TBALL1),
    [StateType.S_TBALLX1]: s('bal1', 32770, 6, undefined, StateType.S_TBALLX2),
    [StateType.S_TBALLX2]: s('bal1', 32771, 6, undefined, StateType.S_TBALLX3),
    [StateType.S_TBALLX3]: s('bal1', 32772, 6, undefined, StateType.S_NULL),
    [StateType.S_RBALL1]: s('bal2', 32768, 4, undefined, StateType.S_RBALL2),
    [StateType.S_RBALL2]: s('bal2', 32769, 4, undefined, StateType.S_RBALL1),
    [StateType.S_RBALLX1]: s('bal2', 32770, 6, undefined, StateType.S_RBALLX2),
    [StateType.S_RBALLX2]: s('bal2', 32771, 6, undefined, StateType.S_RBALLX3),
    [StateType.S_RBALLX3]: s('bal2', 32772, 6, undefined, StateType.S_NULL),
    [StateType.S_PLASBALL]: s('plss', 32768, 6, undefined, StateType.S_PLASBALL2),
    [StateType.S_PLASBALL2]: s('plss', 32769, 6, undefined, StateType.S_PLASBALL),
    [StateType.S_PLASEXP]: s('plse', 32768, 4, undefined, StateType.S_PLASEXP2),
    [StateType.S_PLASEXP2]: s('plse', 32769, 4, undefined, StateType.S_PLASEXP3),
    [StateType.S_PLASEXP3]: s('plse', 32770, 4, undefined, StateType.S_PLASEXP4),
    [StateType.S_PLASEXP4]: s('plse', 32771, 4, undefined, StateType.S_PLASEXP5),
    [StateType.S_PLASEXP5]: s('plse', 32772, 4, undefined, StateType.S_NULL),
    [StateType.S_ROCKET]: s('misl', 32768, 1, undefined, StateType.S_ROCKET),
    [StateType.S_BFGSHOT]: s('bfs1', 32768, 4, undefined, StateType.S_BFGSHOT2),
    [StateType.S_BFGSHOT2]: s('bfs1', 32769, 4, undefined, StateType.S_BFGSHOT),
    [StateType.S_BFGLAND]: s('bfe1', 32768, 8, undefined, StateType.S_BFGLAND2),
    [StateType.S_BFGLAND2]: s('bfe1', 32769, 8, undefined, StateType.S_BFGLAND3),
    [StateType.S_BFGLAND3]: s('bfe1', 32770, 8, A_BFGSpray, StateType.S_BFGLAND4),
    [StateType.S_BFGLAND4]: s('bfe1', 32771, 8, undefined, StateType.S_BFGLAND5),
    [StateType.S_BFGLAND5]: s('bfe1', 32772, 8, undefined, StateType.S_BFGLAND6),
    [StateType.S_BFGLAND6]: s('bfe1', 32773, 8, undefined, StateType.S_NULL),
    [StateType.S_BFGEXP]: s('bfe2', 32768, 8, undefined, StateType.S_BFGEXP2),
    [StateType.S_BFGEXP2]: s('bfe2', 32769, 8, undefined, StateType.S_BFGEXP3),
    [StateType.S_BFGEXP3]: s('bfe2', 32770, 8, undefined, StateType.S_BFGEXP4),
    [StateType.S_BFGEXP4]: s('bfe2', 32771, 8, undefined, StateType.S_NULL),
    [StateType.S_EXPLODE1]: s('misl', 32769, 8, A_Explode, StateType.S_EXPLODE2),
    [StateType.S_EXPLODE2]: s('misl', 32770, 6, undefined, StateType.S_EXPLODE3),
    [StateType.S_EXPLODE3]: s('misl', 32771, 4, undefined, StateType.S_NULL),
    [StateType.S_TFOG]: s('tfog', 32768, 6, undefined, StateType.S_TFOG01),
    [StateType.S_TFOG01]: s('tfog', 32769, 6, undefined, StateType.S_TFOG02),
    [StateType.S_TFOG02]: s('tfog', 32768, 6, undefined, StateType.S_TFOG2),
    [StateType.S_TFOG2]: s('tfog', 32769, 6, undefined, StateType.S_TFOG3),
    [StateType.S_TFOG3]: s('tfog', 32770, 6, undefined, StateType.S_TFOG4),
    [StateType.S_TFOG4]: s('tfog', 32771, 6, undefined, StateType.S_TFOG5),
    [StateType.S_TFOG5]: s('tfog', 32772, 6, undefined, StateType.S_TFOG6),
    [StateType.S_TFOG6]: s('tfog', 32773, 6, undefined, StateType.S_TFOG7),
    [StateType.S_TFOG7]: s('tfog', 32774, 6, undefined, StateType.S_TFOG8),
    [StateType.S_TFOG8]: s('tfog', 32775, 6, undefined, StateType.S_TFOG9),
    [StateType.S_TFOG9]: s('tfog', 32776, 6, undefined, StateType.S_TFOG10),
    [StateType.S_TFOG10]: s('tfog', 32777, 6, undefined, StateType.S_NULL),
    [StateType.S_IFOG]: s('ifog', 32768, 6, undefined, StateType.S_IFOG01),
    [StateType.S_IFOG01]: s('ifog', 32769, 6, undefined, StateType.S_IFOG02),
    [StateType.S_IFOG02]: s('ifog', 32768, 6, undefined, StateType.S_IFOG2),
    [StateType.S_IFOG2]: s('ifog', 32769, 6, undefined, StateType.S_IFOG3),
    [StateType.S_IFOG3]: s('ifog', 32770, 6, undefined, StateType.S_IFOG4),
    [StateType.S_IFOG4]: s('ifog', 32771, 6, undefined, StateType.S_IFOG5),
    [StateType.S_IFOG5]: s('ifog', 32772, 6, undefined, StateType.S_NULL),
    [StateType.S_PLAY]: s('play', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_PLAY_RUN1]: s('play', 0, 4, undefined, StateType.S_PLAY_RUN2),
    [StateType.S_PLAY_RUN2]: s('play', 1, 4, undefined, StateType.S_PLAY_RUN3),
    [StateType.S_PLAY_RUN3]: s('play', 2, 4, undefined, StateType.S_PLAY_RUN4),
    [StateType.S_PLAY_RUN4]: s('play', 3, 4, undefined, StateType.S_PLAY_RUN1),
    [StateType.S_PLAY_ATK1]: s('play', 4, 12, undefined, StateType.S_PLAY),
    [StateType.S_PLAY_ATK2]: s('play', 32773, 6, undefined, StateType.S_PLAY_ATK1),
    [StateType.S_PLAY_PAIN]: s('play', 6, 4, undefined, StateType.S_PLAY_PAIN2),
    [StateType.S_PLAY_PAIN2]: s('play', 6, 4, A_Pain, StateType.S_PLAY),
    [StateType.S_PLAY_DIE1]: s('play', 7, 10, undefined, StateType.S_PLAY_DIE2),
    [StateType.S_PLAY_DIE2]: s('play', 8, 10, A_PlayerScream, StateType.S_PLAY_DIE3),
    [StateType.S_PLAY_DIE3]: s('play', 9, 10, A_Fall, StateType.S_PLAY_DIE4),
    [StateType.S_PLAY_DIE4]: s('play', 10, 10, undefined, StateType.S_PLAY_DIE5),
    [StateType.S_PLAY_DIE5]: s('play', 11, 10, undefined, StateType.S_PLAY_DIE6),
    [StateType.S_PLAY_DIE6]: s('play', 12, 10, undefined, StateType.S_PLAY_DIE7),
    [StateType.S_PLAY_DIE7]: s('play', 13, -1, undefined, StateType.S_NULL),
    [StateType.S_PLAY_XDIE1]: s('play', 14, 5, undefined, StateType.S_PLAY_XDIE2),
    [StateType.S_PLAY_XDIE2]: s('play', 15, 5, A_XScream, StateType.S_PLAY_XDIE3),
    [StateType.S_PLAY_XDIE3]: s('play', 16, 5, A_Fall, StateType.S_PLAY_XDIE4),
    [StateType.S_PLAY_XDIE4]: s('play', 17, 5, undefined, StateType.S_PLAY_XDIE5),
    [StateType.S_PLAY_XDIE5]: s('play', 18, 5, undefined, StateType.S_PLAY_XDIE6),
    [StateType.S_PLAY_XDIE6]: s('play', 19, 5, undefined, StateType.S_PLAY_XDIE7),
    [StateType.S_PLAY_XDIE7]: s('play', 20, 5, undefined, StateType.S_PLAY_XDIE8),
    [StateType.S_PLAY_XDIE8]: s('play', 21, 5, undefined, StateType.S_PLAY_XDIE9),
    [StateType.S_PLAY_XDIE9]: s('play', 22, -1, undefined, StateType.S_NULL),
    [StateType.S_POSS_STND]: s('poss', 0, 10, A_Look, StateType.S_POSS_STND2),
    [StateType.S_POSS_STND2]: s('poss', 1, 10, A_Look, StateType.S_POSS_STND),
    [StateType.S_POSS_RUN1]: s('poss', 0, 4, A_Chase, StateType.S_POSS_RUN2),
    [StateType.S_POSS_RUN2]: s('poss', 0, 4, A_Chase, StateType.S_POSS_RUN3),
    [StateType.S_POSS_RUN3]: s('poss', 1, 4, A_Chase, StateType.S_POSS_RUN4),
    [StateType.S_POSS_RUN4]: s('poss', 1, 4, A_Chase, StateType.S_POSS_RUN5),
    [StateType.S_POSS_RUN5]: s('poss', 2, 4, A_Chase, StateType.S_POSS_RUN6),
    [StateType.S_POSS_RUN6]: s('poss', 2, 4, A_Chase, StateType.S_POSS_RUN7),
    [StateType.S_POSS_RUN7]: s('poss', 3, 4, A_Chase, StateType.S_POSS_RUN8),
    [StateType.S_POSS_RUN8]: s('poss', 3, 4, A_Chase, StateType.S_POSS_RUN1),
    [StateType.S_POSS_ATK1]: s('poss', 4, 10, A_FaceTarget, StateType.S_POSS_ATK2),
    [StateType.S_POSS_ATK2]: s('poss', 5, 8, A_PosAttack, StateType.S_POSS_ATK3),
    [StateType.S_POSS_ATK3]: s('poss', 4, 8, undefined, StateType.S_POSS_RUN1),
    [StateType.S_POSS_PAIN]: s('poss', 6, 3, undefined, StateType.S_POSS_PAIN2),
    [StateType.S_POSS_PAIN2]: s('poss', 6, 3, A_Pain, StateType.S_POSS_RUN1),
    [StateType.S_POSS_DIE1]: s('poss', 7, 5, undefined, StateType.S_POSS_DIE2),
    [StateType.S_POSS_DIE2]: s('poss', 8, 5, A_Scream, StateType.S_POSS_DIE3),
    [StateType.S_POSS_DIE3]: s('poss', 9, 5, A_Fall, StateType.S_POSS_DIE4),
    [StateType.S_POSS_DIE4]: s('poss', 10, 5, undefined, StateType.S_POSS_DIE5),
    [StateType.S_POSS_DIE5]: s('poss', 11, -1, undefined, StateType.S_NULL),
    [StateType.S_POSS_XDIE1]: s('poss', 12, 5, undefined, StateType.S_POSS_XDIE2),
    [StateType.S_POSS_XDIE2]: s('poss', 13, 5, A_XScream, StateType.S_POSS_XDIE3),
    [StateType.S_POSS_XDIE3]: s('poss', 14, 5, A_Fall, StateType.S_POSS_XDIE4),
    [StateType.S_POSS_XDIE4]: s('poss', 15, 5, undefined, StateType.S_POSS_XDIE5),
    [StateType.S_POSS_XDIE5]: s('poss', 16, 5, undefined, StateType.S_POSS_XDIE6),
    [StateType.S_POSS_XDIE6]: s('poss', 17, 5, undefined, StateType.S_POSS_XDIE7),
    [StateType.S_POSS_XDIE7]: s('poss', 18, 5, undefined, StateType.S_POSS_XDIE8),
    [StateType.S_POSS_XDIE8]: s('poss', 19, 5, undefined, StateType.S_POSS_XDIE9),
    [StateType.S_POSS_XDIE9]: s('poss', 20, -1, undefined, StateType.S_NULL),
    [StateType.S_POSS_RAISE1]: s('poss', 10, 5, undefined, StateType.S_POSS_RAISE2),
    [StateType.S_POSS_RAISE2]: s('poss', 9, 5, undefined, StateType.S_POSS_RAISE3),
    [StateType.S_POSS_RAISE3]: s('poss', 8, 5, undefined, StateType.S_POSS_RAISE4),
    [StateType.S_POSS_RAISE4]: s('poss', 7, 5, undefined, StateType.S_POSS_RUN1),
    [StateType.S_SPOS_STND]: s('spos', 0, 10, A_Look, StateType.S_SPOS_STND2),
    [StateType.S_SPOS_STND2]: s('spos', 1, 10, A_Look, StateType.S_SPOS_STND),
    [StateType.S_SPOS_RUN1]: s('spos', 0, 3, A_Chase, StateType.S_SPOS_RUN2),
    [StateType.S_SPOS_RUN2]: s('spos', 0, 3, A_Chase, StateType.S_SPOS_RUN3),
    [StateType.S_SPOS_RUN3]: s('spos', 1, 3, A_Chase, StateType.S_SPOS_RUN4),
    [StateType.S_SPOS_RUN4]: s('spos', 1, 3, A_Chase, StateType.S_SPOS_RUN5),
    [StateType.S_SPOS_RUN5]: s('spos', 2, 3, A_Chase, StateType.S_SPOS_RUN6),
    [StateType.S_SPOS_RUN6]: s('spos', 2, 3, A_Chase, StateType.S_SPOS_RUN7),
    [StateType.S_SPOS_RUN7]: s('spos', 3, 3, A_Chase, StateType.S_SPOS_RUN8),
    [StateType.S_SPOS_RUN8]: s('spos', 3, 3, A_Chase, StateType.S_SPOS_RUN1),
    [StateType.S_SPOS_ATK1]: s('spos', 4, 10, A_FaceTarget, StateType.S_SPOS_ATK2),
    [StateType.S_SPOS_ATK2]: s('spos', 32773, 10, A_SPosAttack, StateType.S_SPOS_ATK3),
    [StateType.S_SPOS_ATK3]: s('spos', 4, 10, undefined, StateType.S_SPOS_RUN1),
    [StateType.S_SPOS_PAIN]: s('spos', 6, 3, undefined, StateType.S_SPOS_PAIN2),
    [StateType.S_SPOS_PAIN2]: s('spos', 6, 3, A_Pain, StateType.S_SPOS_RUN1),
    [StateType.S_SPOS_DIE1]: s('spos', 7, 5, undefined, StateType.S_SPOS_DIE2),
    [StateType.S_SPOS_DIE2]: s('spos', 8, 5, A_Scream, StateType.S_SPOS_DIE3),
    [StateType.S_SPOS_DIE3]: s('spos', 9, 5, A_Fall, StateType.S_SPOS_DIE4),
    [StateType.S_SPOS_DIE4]: s('spos', 10, 5, undefined, StateType.S_SPOS_DIE5),
    [StateType.S_SPOS_DIE5]: s('spos', 11, -1, undefined, StateType.S_NULL),
    [StateType.S_SPOS_XDIE1]: s('spos', 12, 5, undefined, StateType.S_SPOS_XDIE2),
    [StateType.S_SPOS_XDIE2]: s('spos', 13, 5, A_XScream, StateType.S_SPOS_XDIE3),
    [StateType.S_SPOS_XDIE3]: s('spos', 14, 5, A_Fall, StateType.S_SPOS_XDIE4),
    [StateType.S_SPOS_XDIE4]: s('spos', 15, 5, undefined, StateType.S_SPOS_XDIE5),
    [StateType.S_SPOS_XDIE5]: s('spos', 16, 5, undefined, StateType.S_SPOS_XDIE6),
    [StateType.S_SPOS_XDIE6]: s('spos', 17, 5, undefined, StateType.S_SPOS_XDIE7),
    [StateType.S_SPOS_XDIE7]: s('spos', 18, 5, undefined, StateType.S_SPOS_XDIE8),
    [StateType.S_SPOS_XDIE8]: s('spos', 19, 5, undefined, StateType.S_SPOS_XDIE9),
    [StateType.S_SPOS_XDIE9]: s('spos', 20, -1, undefined, StateType.S_NULL),
    [StateType.S_SPOS_RAISE1]: s('spos', 11, 5, undefined, StateType.S_SPOS_RAISE2),
    [StateType.S_SPOS_RAISE2]: s('spos', 10, 5, undefined, StateType.S_SPOS_RAISE3),
    [StateType.S_SPOS_RAISE3]: s('spos', 9, 5, undefined, StateType.S_SPOS_RAISE4),
    [StateType.S_SPOS_RAISE4]: s('spos', 8, 5, undefined, StateType.S_SPOS_RAISE5),
    [StateType.S_SPOS_RAISE5]: s('spos', 7, 5, undefined, StateType.S_SPOS_RUN1),
    [StateType.S_VILE_STND]: s('vile', 0, 10, A_Look, StateType.S_VILE_STND2),
    [StateType.S_VILE_STND2]: s('vile', 1, 10, A_Look, StateType.S_VILE_STND),
    [StateType.S_VILE_RUN1]: s('vile', 0, 2, A_VileChase, StateType.S_VILE_RUN2),
    [StateType.S_VILE_RUN2]: s('vile', 0, 2, A_VileChase, StateType.S_VILE_RUN3),
    [StateType.S_VILE_RUN3]: s('vile', 1, 2, A_VileChase, StateType.S_VILE_RUN4),
    [StateType.S_VILE_RUN4]: s('vile', 1, 2, A_VileChase, StateType.S_VILE_RUN5),
    [StateType.S_VILE_RUN5]: s('vile', 2, 2, A_VileChase, StateType.S_VILE_RUN6),
    [StateType.S_VILE_RUN6]: s('vile', 2, 2, A_VileChase, StateType.S_VILE_RUN7),
    [StateType.S_VILE_RUN7]: s('vile', 3, 2, A_VileChase, StateType.S_VILE_RUN8),
    [StateType.S_VILE_RUN8]: s('vile', 3, 2, A_VileChase, StateType.S_VILE_RUN9),
    [StateType.S_VILE_RUN9]: s('vile', 4, 2, A_VileChase, StateType.S_VILE_RUN10),
    [StateType.S_VILE_RUN10]: s('vile', 4, 2, A_VileChase, StateType.S_VILE_RUN11),
    [StateType.S_VILE_RUN11]: s('vile', 5, 2, A_VileChase, StateType.S_VILE_RUN12),
    [StateType.S_VILE_RUN12]: s('vile', 5, 2, A_VileChase, StateType.S_VILE_RUN1),
    [StateType.S_VILE_ATK1]: s('vile', 32774, 0, A_VileStart, StateType.S_VILE_ATK2),
    [StateType.S_VILE_ATK2]: s('vile', 32774, 10, A_FaceTarget, StateType.S_VILE_ATK3),
    [StateType.S_VILE_ATK3]: s('vile', 32775, 8, A_VileTarget, StateType.S_VILE_ATK4),
    [StateType.S_VILE_ATK4]: s('vile', 32776, 8, A_FaceTarget, StateType.S_VILE_ATK5),
    [StateType.S_VILE_ATK5]: s('vile', 32777, 8, A_FaceTarget, StateType.S_VILE_ATK6),
    [StateType.S_VILE_ATK6]: s('vile', 32778, 8, A_FaceTarget, StateType.S_VILE_ATK7),
    [StateType.S_VILE_ATK7]: s('vile', 32779, 8, A_FaceTarget, StateType.S_VILE_ATK8),
    [StateType.S_VILE_ATK8]: s('vile', 32780, 8, A_FaceTarget, StateType.S_VILE_ATK9),
    [StateType.S_VILE_ATK9]: s('vile', 32781, 8, A_FaceTarget, StateType.S_VILE_ATK10),
    [StateType.S_VILE_ATK10]: s('vile', 32782, 8, A_VileAttack, StateType.S_VILE_ATK11),
    [StateType.S_VILE_ATK11]: s('vile', 32783, 20, undefined, StateType.S_VILE_RUN1),
    [StateType.S_VILE_HEAL1]: s('vile', 32794, 10, undefined, StateType.S_VILE_HEAL2),
    [StateType.S_VILE_HEAL2]: s('vile', 32795, 10, undefined, StateType.S_VILE_HEAL3),
    [StateType.S_VILE_HEAL3]: s('vile', 32796, 10, undefined, StateType.S_VILE_RUN1),
    [StateType.S_VILE_PAIN]: s('vile', 16, 5, undefined, StateType.S_VILE_PAIN2),
    [StateType.S_VILE_PAIN2]: s('vile', 16, 5, A_Pain, StateType.S_VILE_RUN1),
    [StateType.S_VILE_DIE1]: s('vile', 16, 7, undefined, StateType.S_VILE_DIE2),
    [StateType.S_VILE_DIE2]: s('vile', 17, 7, A_Scream, StateType.S_VILE_DIE3),
    [StateType.S_VILE_DIE3]: s('vile', 18, 7, A_Fall, StateType.S_VILE_DIE4),
    [StateType.S_VILE_DIE4]: s('vile', 19, 7, undefined, StateType.S_VILE_DIE5),
    [StateType.S_VILE_DIE5]: s('vile', 20, 7, undefined, StateType.S_VILE_DIE6),
    [StateType.S_VILE_DIE6]: s('vile', 21, 7, undefined, StateType.S_VILE_DIE7),
    [StateType.S_VILE_DIE7]: s('vile', 22, 7, undefined, StateType.S_VILE_DIE8),
    [StateType.S_VILE_DIE8]: s('vile', 23, 5, undefined, StateType.S_VILE_DIE9),
    [StateType.S_VILE_DIE9]: s('vile', 24, 5, undefined, StateType.S_VILE_DIE10),
    [StateType.S_VILE_DIE10]: s('vile', 25, -1, undefined, StateType.S_NULL),
    [StateType.S_FIRE1]: s('fire', 32768, 2, A_StartFire, StateType.S_FIRE2),
    [StateType.S_FIRE2]: s('fire', 32769, 2, A_Fire, StateType.S_FIRE3),
    [StateType.S_FIRE3]: s('fire', 32768, 2, A_Fire, StateType.S_FIRE4),
    [StateType.S_FIRE4]: s('fire', 32769, 2, A_Fire, StateType.S_FIRE5),
    [StateType.S_FIRE5]: s('fire', 32770, 2, A_FireCrackle, StateType.S_FIRE6),
    [StateType.S_FIRE6]: s('fire', 32769, 2, A_Fire, StateType.S_FIRE7),
    [StateType.S_FIRE7]: s('fire', 32770, 2, A_Fire, StateType.S_FIRE8),
    [StateType.S_FIRE8]: s('fire', 32769, 2, A_Fire, StateType.S_FIRE9),
    [StateType.S_FIRE9]: s('fire', 32770, 2, A_Fire, StateType.S_FIRE10),
    [StateType.S_FIRE10]: s('fire', 32771, 2, A_Fire, StateType.S_FIRE11),
    [StateType.S_FIRE11]: s('fire', 32770, 2, A_Fire, StateType.S_FIRE12),
    [StateType.S_FIRE12]: s('fire', 32771, 2, A_Fire, StateType.S_FIRE13),
    [StateType.S_FIRE13]: s('fire', 32770, 2, A_Fire, StateType.S_FIRE14),
    [StateType.S_FIRE14]: s('fire', 32771, 2, A_Fire, StateType.S_FIRE15),
    [StateType.S_FIRE15]: s('fire', 32772, 2, A_Fire, StateType.S_FIRE16),
    [StateType.S_FIRE16]: s('fire', 32771, 2, A_Fire, StateType.S_FIRE17),
    [StateType.S_FIRE17]: s('fire', 32772, 2, A_Fire, StateType.S_FIRE18),
    [StateType.S_FIRE18]: s('fire', 32771, 2, A_Fire, StateType.S_FIRE19),
    [StateType.S_FIRE19]: s('fire', 32772, 2, A_FireCrackle, StateType.S_FIRE20),
    [StateType.S_FIRE20]: s('fire', 32773, 2, A_Fire, StateType.S_FIRE21),
    [StateType.S_FIRE21]: s('fire', 32772, 2, A_Fire, StateType.S_FIRE22),
    [StateType.S_FIRE22]: s('fire', 32773, 2, A_Fire, StateType.S_FIRE23),
    [StateType.S_FIRE23]: s('fire', 32772, 2, A_Fire, StateType.S_FIRE24),
    [StateType.S_FIRE24]: s('fire', 32773, 2, A_Fire, StateType.S_FIRE25),
    [StateType.S_FIRE25]: s('fire', 32774, 2, A_Fire, StateType.S_FIRE26),
    [StateType.S_FIRE26]: s('fire', 32775, 2, A_Fire, StateType.S_FIRE27),
    [StateType.S_FIRE27]: s('fire', 32774, 2, A_Fire, StateType.S_FIRE28),
    [StateType.S_FIRE28]: s('fire', 32775, 2, A_Fire, StateType.S_FIRE29),
    [StateType.S_FIRE29]: s('fire', 32774, 2, A_Fire, StateType.S_FIRE30),
    [StateType.S_FIRE30]: s('fire', 32775, 2, A_Fire, StateType.S_NULL),
    [StateType.S_SMOKE1]: s('puff', 1, 4, undefined, StateType.S_SMOKE2),
    [StateType.S_SMOKE2]: s('puff', 2, 4, undefined, StateType.S_SMOKE3),
    [StateType.S_SMOKE3]: s('puff', 1, 4, undefined, StateType.S_SMOKE4),
    [StateType.S_SMOKE4]: s('puff', 2, 4, undefined, StateType.S_SMOKE5),
    [StateType.S_SMOKE5]: s('puff', 3, 4, undefined, StateType.S_NULL),
    [StateType.S_TRACER]: s('fatb', 32768, 2, A_Tracer, StateType.S_TRACER2),
    [StateType.S_TRACER2]: s('fatb', 32769, 2, A_Tracer, StateType.S_TRACER),
    [StateType.S_TRACEEXP1]: s('fbxp', 32768, 8, undefined, StateType.S_TRACEEXP2),
    [StateType.S_TRACEEXP2]: s('fbxp', 32769, 6, undefined, StateType.S_TRACEEXP3),
    [StateType.S_TRACEEXP3]: s('fbxp', 32770, 4, undefined, StateType.S_NULL),
    [StateType.S_SKEL_STND]: s('skel', 0, 10, A_Look, StateType.S_SKEL_STND2),
    [StateType.S_SKEL_STND2]: s('skel', 1, 10, A_Look, StateType.S_SKEL_STND),
    [StateType.S_SKEL_RUN1]: s('skel', 0, 2, A_Chase, StateType.S_SKEL_RUN2),
    [StateType.S_SKEL_RUN2]: s('skel', 0, 2, A_Chase, StateType.S_SKEL_RUN3),
    [StateType.S_SKEL_RUN3]: s('skel', 1, 2, A_Chase, StateType.S_SKEL_RUN4),
    [StateType.S_SKEL_RUN4]: s('skel', 1, 2, A_Chase, StateType.S_SKEL_RUN5),
    [StateType.S_SKEL_RUN5]: s('skel', 2, 2, A_Chase, StateType.S_SKEL_RUN6),
    [StateType.S_SKEL_RUN6]: s('skel', 2, 2, A_Chase, StateType.S_SKEL_RUN7),
    [StateType.S_SKEL_RUN7]: s('skel', 3, 2, A_Chase, StateType.S_SKEL_RUN8),
    [StateType.S_SKEL_RUN8]: s('skel', 3, 2, A_Chase, StateType.S_SKEL_RUN9),
    [StateType.S_SKEL_RUN9]: s('skel', 4, 2, A_Chase, StateType.S_SKEL_RUN10),
    [StateType.S_SKEL_RUN10]: s('skel', 4, 2, A_Chase, StateType.S_SKEL_RUN11),
    [StateType.S_SKEL_RUN11]: s('skel', 5, 2, A_Chase, StateType.S_SKEL_RUN12),
    [StateType.S_SKEL_RUN12]: s('skel', 5, 2, A_Chase, StateType.S_SKEL_RUN1),
    [StateType.S_SKEL_FIST1]: s('skel', 6, 0, A_FaceTarget, StateType.S_SKEL_FIST2),
    [StateType.S_SKEL_FIST2]: s('skel', 6, 6, A_SkelWhoosh, StateType.S_SKEL_FIST3),
    [StateType.S_SKEL_FIST3]: s('skel', 7, 6, A_FaceTarget, StateType.S_SKEL_FIST4),
    [StateType.S_SKEL_FIST4]: s('skel', 8, 6, A_SkelFist, StateType.S_SKEL_RUN1),
    [StateType.S_SKEL_MISS1]: s('skel', 32777, 0, A_FaceTarget, StateType.S_SKEL_MISS2),
    [StateType.S_SKEL_MISS2]: s('skel', 32777, 10, A_FaceTarget, StateType.S_SKEL_MISS3),
    [StateType.S_SKEL_MISS3]: s('skel', 10, 10, A_SkelMissile, StateType.S_SKEL_MISS4),
    [StateType.S_SKEL_MISS4]: s('skel', 10, 10, A_FaceTarget, StateType.S_SKEL_RUN1),
    [StateType.S_SKEL_PAIN]: s('skel', 11, 5, undefined, StateType.S_SKEL_PAIN2),
    [StateType.S_SKEL_PAIN2]: s('skel', 11, 5, A_Pain, StateType.S_SKEL_RUN1),
    [StateType.S_SKEL_DIE1]: s('skel', 11, 7, undefined, StateType.S_SKEL_DIE2),
    [StateType.S_SKEL_DIE2]: s('skel', 12, 7, undefined, StateType.S_SKEL_DIE3),
    [StateType.S_SKEL_DIE3]: s('skel', 13, 7, A_Scream, StateType.S_SKEL_DIE4),
    [StateType.S_SKEL_DIE4]: s('skel', 14, 7, A_Fall, StateType.S_SKEL_DIE5),
    [StateType.S_SKEL_DIE5]: s('skel', 15, 7, undefined, StateType.S_SKEL_DIE6),
    [StateType.S_SKEL_DIE6]: s('skel', 16, -1, undefined, StateType.S_NULL),
    [StateType.S_SKEL_RAISE1]: s('skel', 16, 5, undefined, StateType.S_SKEL_RAISE2),
    [StateType.S_SKEL_RAISE2]: s('skel', 15, 5, undefined, StateType.S_SKEL_RAISE3),
    [StateType.S_SKEL_RAISE3]: s('skel', 14, 5, undefined, StateType.S_SKEL_RAISE4),
    [StateType.S_SKEL_RAISE4]: s('skel', 13, 5, undefined, StateType.S_SKEL_RAISE5),
    [StateType.S_SKEL_RAISE5]: s('skel', 12, 5, undefined, StateType.S_SKEL_RAISE6),
    [StateType.S_SKEL_RAISE6]: s('skel', 11, 5, undefined, StateType.S_SKEL_RUN1),
    [StateType.S_FATSHOT1]: s('manf', 32768, 4, undefined, StateType.S_FATSHOT2),
    [StateType.S_FATSHOT2]: s('manf', 32769, 4, undefined, StateType.S_FATSHOT1),
    [StateType.S_FATSHOTX1]: s('misl', 32769, 8, undefined, StateType.S_FATSHOTX2),
    [StateType.S_FATSHOTX2]: s('misl', 32770, 6, undefined, StateType.S_FATSHOTX3),
    [StateType.S_FATSHOTX3]: s('misl', 32771, 4, undefined, StateType.S_NULL),
    [StateType.S_FATT_STND]: s('fatt', 0, 15, A_Look, StateType.S_FATT_STND2),
    [StateType.S_FATT_STND2]: s('fatt', 1, 15, A_Look, StateType.S_FATT_STND),
    [StateType.S_FATT_RUN1]: s('fatt', 0, 4, A_Chase, StateType.S_FATT_RUN2),
    [StateType.S_FATT_RUN2]: s('fatt', 0, 4, A_Chase, StateType.S_FATT_RUN3),
    [StateType.S_FATT_RUN3]: s('fatt', 1, 4, A_Chase, StateType.S_FATT_RUN4),
    [StateType.S_FATT_RUN4]: s('fatt', 1, 4, A_Chase, StateType.S_FATT_RUN5),
    [StateType.S_FATT_RUN5]: s('fatt', 2, 4, A_Chase, StateType.S_FATT_RUN6),
    [StateType.S_FATT_RUN6]: s('fatt', 2, 4, A_Chase, StateType.S_FATT_RUN7),
    [StateType.S_FATT_RUN7]: s('fatt', 3, 4, A_Chase, StateType.S_FATT_RUN8),
    [StateType.S_FATT_RUN8]: s('fatt', 3, 4, A_Chase, StateType.S_FATT_RUN9),
    [StateType.S_FATT_RUN9]: s('fatt', 4, 4, A_Chase, StateType.S_FATT_RUN10),
    [StateType.S_FATT_RUN10]: s('fatt', 4, 4, A_Chase, StateType.S_FATT_RUN11),
    [StateType.S_FATT_RUN11]: s('fatt', 5, 4, A_Chase, StateType.S_FATT_RUN12),
    [StateType.S_FATT_RUN12]: s('fatt', 5, 4, A_Chase, StateType.S_FATT_RUN1),
    [StateType.S_FATT_ATK1]: s('fatt', 6, 20, A_FatRaise, StateType.S_FATT_ATK2),
    [StateType.S_FATT_ATK2]: s('fatt', 32775, 10, A_FatAttack1, StateType.S_FATT_ATK3),
    [StateType.S_FATT_ATK3]: s('fatt', 8, 5, A_FaceTarget, StateType.S_FATT_ATK4),
    [StateType.S_FATT_ATK4]: s('fatt', 6, 5, A_FaceTarget, StateType.S_FATT_ATK5),
    [StateType.S_FATT_ATK5]: s('fatt', 32775, 10, A_FatAttack2, StateType.S_FATT_ATK6),
    [StateType.S_FATT_ATK6]: s('fatt', 8, 5, A_FaceTarget, StateType.S_FATT_ATK7),
    [StateType.S_FATT_ATK7]: s('fatt', 6, 5, A_FaceTarget, StateType.S_FATT_ATK8),
    [StateType.S_FATT_ATK8]: s('fatt', 32775, 10, A_FatAttack3, StateType.S_FATT_ATK9),
    [StateType.S_FATT_ATK9]: s('fatt', 8, 5, A_FaceTarget, StateType.S_FATT_ATK10),
    [StateType.S_FATT_ATK10]: s('fatt', 6, 5, A_FaceTarget, StateType.S_FATT_RUN1),
    [StateType.S_FATT_PAIN]: s('fatt', 9, 3, undefined, StateType.S_FATT_PAIN2),
    [StateType.S_FATT_PAIN2]: s('fatt', 9, 3, A_Pain, StateType.S_FATT_RUN1),
    [StateType.S_FATT_DIE1]: s('fatt', 10, 6, undefined, StateType.S_FATT_DIE2),
    [StateType.S_FATT_DIE2]: s('fatt', 11, 6, A_Scream, StateType.S_FATT_DIE3),
    [StateType.S_FATT_DIE3]: s('fatt', 12, 6, A_Fall, StateType.S_FATT_DIE4),
    [StateType.S_FATT_DIE4]: s('fatt', 13, 6, undefined, StateType.S_FATT_DIE5),
    [StateType.S_FATT_DIE5]: s('fatt', 14, 6, undefined, StateType.S_FATT_DIE6),
    [StateType.S_FATT_DIE6]: s('fatt', 15, 6, undefined, StateType.S_FATT_DIE7),
    [StateType.S_FATT_DIE7]: s('fatt', 16, 6, undefined, StateType.S_FATT_DIE8),
    [StateType.S_FATT_DIE8]: s('fatt', 17, 6, undefined, StateType.S_FATT_DIE9),
    [StateType.S_FATT_DIE9]: s('fatt', 18, 6, undefined, StateType.S_FATT_DIE10),
    [StateType.S_FATT_DIE10]: s('fatt', 19, -1, A_BossDeath, StateType.S_NULL),
    [StateType.S_FATT_RAISE1]: s('fatt', 17, 5, undefined, StateType.S_FATT_RAISE2),
    [StateType.S_FATT_RAISE2]: s('fatt', 16, 5, undefined, StateType.S_FATT_RAISE3),
    [StateType.S_FATT_RAISE3]: s('fatt', 15, 5, undefined, StateType.S_FATT_RAISE4),
    [StateType.S_FATT_RAISE4]: s('fatt', 14, 5, undefined, StateType.S_FATT_RAISE5),
    [StateType.S_FATT_RAISE5]: s('fatt', 13, 5, undefined, StateType.S_FATT_RAISE6),
    [StateType.S_FATT_RAISE6]: s('fatt', 12, 5, undefined, StateType.S_FATT_RAISE7),
    [StateType.S_FATT_RAISE7]: s('fatt', 11, 5, undefined, StateType.S_FATT_RAISE8),
    [StateType.S_FATT_RAISE8]: s('fatt', 10, 5, undefined, StateType.S_FATT_RUN1),
    [StateType.S_CPOS_STND]: s('cpos', 0, 10, A_Look, StateType.S_CPOS_STND2),
    [StateType.S_CPOS_STND2]: s('cpos', 1, 10, A_Look, StateType.S_CPOS_STND),
    [StateType.S_CPOS_RUN1]: s('cpos', 0, 3, A_Chase, StateType.S_CPOS_RUN2),
    [StateType.S_CPOS_RUN2]: s('cpos', 0, 3, A_Chase, StateType.S_CPOS_RUN3),
    [StateType.S_CPOS_RUN3]: s('cpos', 1, 3, A_Chase, StateType.S_CPOS_RUN4),
    [StateType.S_CPOS_RUN4]: s('cpos', 1, 3, A_Chase, StateType.S_CPOS_RUN5),
    [StateType.S_CPOS_RUN5]: s('cpos', 2, 3, A_Chase, StateType.S_CPOS_RUN6),
    [StateType.S_CPOS_RUN6]: s('cpos', 2, 3, A_Chase, StateType.S_CPOS_RUN7),
    [StateType.S_CPOS_RUN7]: s('cpos', 3, 3, A_Chase, StateType.S_CPOS_RUN8),
    [StateType.S_CPOS_RUN8]: s('cpos', 3, 3, A_Chase, StateType.S_CPOS_RUN1),
    [StateType.S_CPOS_ATK1]: s('cpos', 4, 10, A_FaceTarget, StateType.S_CPOS_ATK2),
    [StateType.S_CPOS_ATK2]: s('cpos', 32773, 4, A_CPosAttack, StateType.S_CPOS_ATK3),
    [StateType.S_CPOS_ATK3]: s('cpos', 32772, 4, A_CPosAttack, StateType.S_CPOS_ATK4),
    [StateType.S_CPOS_ATK4]: s('cpos', 5, 1, A_CPosRefire, StateType.S_CPOS_ATK2),
    [StateType.S_CPOS_PAIN]: s('cpos', 6, 3, undefined, StateType.S_CPOS_PAIN2),
    [StateType.S_CPOS_PAIN2]: s('cpos', 6, 3, A_Pain, StateType.S_CPOS_RUN1),
    [StateType.S_CPOS_DIE1]: s('cpos', 7, 5, undefined, StateType.S_CPOS_DIE2),
    [StateType.S_CPOS_DIE2]: s('cpos', 8, 5, A_Scream, StateType.S_CPOS_DIE3),
    [StateType.S_CPOS_DIE3]: s('cpos', 9, 5, A_Fall, StateType.S_CPOS_DIE4),
    [StateType.S_CPOS_DIE4]: s('cpos', 10, 5, undefined, StateType.S_CPOS_DIE5),
    [StateType.S_CPOS_DIE5]: s('cpos', 11, 5, undefined, StateType.S_CPOS_DIE6),
    [StateType.S_CPOS_DIE6]: s('cpos', 12, 5, undefined, StateType.S_CPOS_DIE7),
    [StateType.S_CPOS_DIE7]: s('cpos', 13, -1, undefined, StateType.S_NULL),
    [StateType.S_CPOS_XDIE1]: s('cpos', 14, 5, undefined, StateType.S_CPOS_XDIE2),
    [StateType.S_CPOS_XDIE2]: s('cpos', 15, 5, A_XScream, StateType.S_CPOS_XDIE3),
    [StateType.S_CPOS_XDIE3]: s('cpos', 16, 5, A_Fall, StateType.S_CPOS_XDIE4),
    [StateType.S_CPOS_XDIE4]: s('cpos', 17, 5, undefined, StateType.S_CPOS_XDIE5),
    [StateType.S_CPOS_XDIE5]: s('cpos', 18, 5, undefined, StateType.S_CPOS_XDIE6),
    [StateType.S_CPOS_XDIE6]: s('cpos', 19, -1, undefined, StateType.S_NULL),
    [StateType.S_CPOS_RAISE1]: s('cpos', 13, 5, undefined, StateType.S_CPOS_RAISE2),
    [StateType.S_CPOS_RAISE2]: s('cpos', 12, 5, undefined, StateType.S_CPOS_RAISE3),
    [StateType.S_CPOS_RAISE3]: s('cpos', 11, 5, undefined, StateType.S_CPOS_RAISE4),
    [StateType.S_CPOS_RAISE4]: s('cpos', 10, 5, undefined, StateType.S_CPOS_RAISE5),
    [StateType.S_CPOS_RAISE5]: s('cpos', 9, 5, undefined, StateType.S_CPOS_RAISE6),
    [StateType.S_CPOS_RAISE6]: s('cpos', 8, 5, undefined, StateType.S_CPOS_RAISE7),
    [StateType.S_CPOS_RAISE7]: s('cpos', 7, 5, undefined, StateType.S_CPOS_RUN1),
    [StateType.S_TROO_STND]: s('troo', 0, 10, A_Look, StateType.S_TROO_STND2),
    [StateType.S_TROO_STND2]: s('troo', 1, 10, A_Look, StateType.S_TROO_STND),
    [StateType.S_TROO_RUN1]: s('troo', 0, 3, A_Chase, StateType.S_TROO_RUN2),
    [StateType.S_TROO_RUN2]: s('troo', 0, 3, A_Chase, StateType.S_TROO_RUN3),
    [StateType.S_TROO_RUN3]: s('troo', 1, 3, A_Chase, StateType.S_TROO_RUN4),
    [StateType.S_TROO_RUN4]: s('troo', 1, 3, A_Chase, StateType.S_TROO_RUN5),
    [StateType.S_TROO_RUN5]: s('troo', 2, 3, A_Chase, StateType.S_TROO_RUN6),
    [StateType.S_TROO_RUN6]: s('troo', 2, 3, A_Chase, StateType.S_TROO_RUN7),
    [StateType.S_TROO_RUN7]: s('troo', 3, 3, A_Chase, StateType.S_TROO_RUN8),
    [StateType.S_TROO_RUN8]: s('troo', 3, 3, A_Chase, StateType.S_TROO_RUN1),
    [StateType.S_TROO_ATK1]: s('troo', 4, 8, A_FaceTarget, StateType.S_TROO_ATK2),
    [StateType.S_TROO_ATK2]: s('troo', 5, 8, A_FaceTarget, StateType.S_TROO_ATK3),
    [StateType.S_TROO_ATK3]: s('troo', 6, 6, A_TroopAttack, StateType.S_TROO_RUN1),
    [StateType.S_TROO_PAIN]: s('troo', 7, 2, undefined, StateType.S_TROO_PAIN2),
    [StateType.S_TROO_PAIN2]: s('troo', 7, 2, A_Pain, StateType.S_TROO_RUN1),
    [StateType.S_TROO_DIE1]: s('troo', 8, 8, undefined, StateType.S_TROO_DIE2),
    [StateType.S_TROO_DIE2]: s('troo', 9, 8, A_Scream, StateType.S_TROO_DIE3),
    [StateType.S_TROO_DIE3]: s('troo', 10, 6, undefined, StateType.S_TROO_DIE4),
    [StateType.S_TROO_DIE4]: s('troo', 11, 6, A_Fall, StateType.S_TROO_DIE5),
    [StateType.S_TROO_DIE5]: s('troo', 12, -1, undefined, StateType.S_NULL),
    [StateType.S_TROO_XDIE1]: s('troo', 13, 5, undefined, StateType.S_TROO_XDIE2),
    [StateType.S_TROO_XDIE2]: s('troo', 14, 5, A_XScream, StateType.S_TROO_XDIE3),
    [StateType.S_TROO_XDIE3]: s('troo', 15, 5, undefined, StateType.S_TROO_XDIE4),
    [StateType.S_TROO_XDIE4]: s('troo', 16, 5, A_Fall, StateType.S_TROO_XDIE5),
    [StateType.S_TROO_XDIE5]: s('troo', 17, 5, undefined, StateType.S_TROO_XDIE6),
    [StateType.S_TROO_XDIE6]: s('troo', 18, 5, undefined, StateType.S_TROO_XDIE7),
    [StateType.S_TROO_XDIE7]: s('troo', 19, 5, undefined, StateType.S_TROO_XDIE8),
    [StateType.S_TROO_XDIE8]: s('troo', 20, -1, undefined, StateType.S_NULL),
    [StateType.S_TROO_RAISE1]: s('troo', 12, 8, undefined, StateType.S_TROO_RAISE2),
    [StateType.S_TROO_RAISE2]: s('troo', 11, 8, undefined, StateType.S_TROO_RAISE3),
    [StateType.S_TROO_RAISE3]: s('troo', 10, 6, undefined, StateType.S_TROO_RAISE4),
    [StateType.S_TROO_RAISE4]: s('troo', 9, 6, undefined, StateType.S_TROO_RAISE5),
    [StateType.S_TROO_RAISE5]: s('troo', 8, 6, undefined, StateType.S_TROO_RUN1),
    [StateType.S_SARG_STND]: s('sarg', 0, 10, A_Look, StateType.S_SARG_STND2),
    [StateType.S_SARG_STND2]: s('sarg', 1, 10, A_Look, StateType.S_SARG_STND),
    [StateType.S_SARG_RUN1]: s('sarg', 0, 2, A_Chase, StateType.S_SARG_RUN2),
    [StateType.S_SARG_RUN2]: s('sarg', 0, 2, A_Chase, StateType.S_SARG_RUN3),
    [StateType.S_SARG_RUN3]: s('sarg', 1, 2, A_Chase, StateType.S_SARG_RUN4),
    [StateType.S_SARG_RUN4]: s('sarg', 1, 2, A_Chase, StateType.S_SARG_RUN5),
    [StateType.S_SARG_RUN5]: s('sarg', 2, 2, A_Chase, StateType.S_SARG_RUN6),
    [StateType.S_SARG_RUN6]: s('sarg', 2, 2, A_Chase, StateType.S_SARG_RUN7),
    [StateType.S_SARG_RUN7]: s('sarg', 3, 2, A_Chase, StateType.S_SARG_RUN8),
    [StateType.S_SARG_RUN8]: s('sarg', 3, 2, A_Chase, StateType.S_SARG_RUN1),
    [StateType.S_SARG_ATK1]: s('sarg', 4, 8, A_FaceTarget, StateType.S_SARG_ATK2),
    [StateType.S_SARG_ATK2]: s('sarg', 5, 8, A_FaceTarget, StateType.S_SARG_ATK3),
    [StateType.S_SARG_ATK3]: s('sarg', 6, 8, A_SargAttack, StateType.S_SARG_RUN1),
    [StateType.S_SARG_PAIN]: s('sarg', 7, 2, undefined, StateType.S_SARG_PAIN2),
    [StateType.S_SARG_PAIN2]: s('sarg', 7, 2, A_Pain, StateType.S_SARG_RUN1),
    [StateType.S_SARG_DIE1]: s('sarg', 8, 8, undefined, StateType.S_SARG_DIE2),
    [StateType.S_SARG_DIE2]: s('sarg', 9, 8, A_Scream, StateType.S_SARG_DIE3),
    [StateType.S_SARG_DIE3]: s('sarg', 10, 4, undefined, StateType.S_SARG_DIE4),
    [StateType.S_SARG_DIE4]: s('sarg', 11, 4, A_Fall, StateType.S_SARG_DIE5),
    [StateType.S_SARG_DIE5]: s('sarg', 12, 4, undefined, StateType.S_SARG_DIE6),
    [StateType.S_SARG_DIE6]: s('sarg', 13, -1, undefined, StateType.S_NULL),
    [StateType.S_SARG_RAISE1]: s('sarg', 13, 5, undefined, StateType.S_SARG_RAISE2),
    [StateType.S_SARG_RAISE2]: s('sarg', 12, 5, undefined, StateType.S_SARG_RAISE3),
    [StateType.S_SARG_RAISE3]: s('sarg', 11, 5, undefined, StateType.S_SARG_RAISE4),
    [StateType.S_SARG_RAISE4]: s('sarg', 10, 5, undefined, StateType.S_SARG_RAISE5),
    [StateType.S_SARG_RAISE5]: s('sarg', 9, 5, undefined, StateType.S_SARG_RAISE6),
    [StateType.S_SARG_RAISE6]: s('sarg', 8, 5, undefined, StateType.S_SARG_RUN1),
    [StateType.S_HEAD_STND]: s('head', 0, 10, A_Look, StateType.S_HEAD_STND),
    [StateType.S_HEAD_RUN1]: s('head', 0, 3, A_Chase, StateType.S_HEAD_RUN1),
    [StateType.S_HEAD_ATK1]: s('head', 1, 5, A_FaceTarget, StateType.S_HEAD_ATK2),
    [StateType.S_HEAD_ATK2]: s('head', 2, 5, A_FaceTarget, StateType.S_HEAD_ATK3),
    [StateType.S_HEAD_ATK3]: s('head', 32771, 5, A_HeadAttack, StateType.S_HEAD_RUN1),
    [StateType.S_HEAD_PAIN]: s('head', 4, 3, undefined, StateType.S_HEAD_PAIN2),
    [StateType.S_HEAD_PAIN2]: s('head', 4, 3, A_Pain, StateType.S_HEAD_PAIN3),
    [StateType.S_HEAD_PAIN3]: s('head', 5, 6, undefined, StateType.S_HEAD_RUN1),
    [StateType.S_HEAD_DIE1]: s('head', 6, 8, undefined, StateType.S_HEAD_DIE2),
    [StateType.S_HEAD_DIE2]: s('head', 7, 8, A_Scream, StateType.S_HEAD_DIE3),
    [StateType.S_HEAD_DIE3]: s('head', 8, 8, undefined, StateType.S_HEAD_DIE4),
    [StateType.S_HEAD_DIE4]: s('head', 9, 8, undefined, StateType.S_HEAD_DIE5),
    [StateType.S_HEAD_DIE5]: s('head', 10, 8, A_Fall, StateType.S_HEAD_DIE6),
    [StateType.S_HEAD_DIE6]: s('head', 11, -1, undefined, StateType.S_NULL),
    [StateType.S_HEAD_RAISE1]: s('head', 11, 8, undefined, StateType.S_HEAD_RAISE2),
    [StateType.S_HEAD_RAISE2]: s('head', 10, 8, undefined, StateType.S_HEAD_RAISE3),
    [StateType.S_HEAD_RAISE3]: s('head', 9, 8, undefined, StateType.S_HEAD_RAISE4),
    [StateType.S_HEAD_RAISE4]: s('head', 8, 8, undefined, StateType.S_HEAD_RAISE5),
    [StateType.S_HEAD_RAISE5]: s('head', 7, 8, undefined, StateType.S_HEAD_RAISE6),
    [StateType.S_HEAD_RAISE6]: s('head', 6, 8, undefined, StateType.S_HEAD_RUN1),
    [StateType.S_BRBALL1]: s('bal7', 32768, 4, undefined, StateType.S_BRBALL2),
    [StateType.S_BRBALL2]: s('bal7', 32769, 4, undefined, StateType.S_BRBALL1),
    [StateType.S_BRBALLX1]: s('bal7', 32770, 6, undefined, StateType.S_BRBALLX2),
    [StateType.S_BRBALLX2]: s('bal7', 32771, 6, undefined, StateType.S_BRBALLX3),
    [StateType.S_BRBALLX3]: s('bal7', 32772, 6, undefined, StateType.S_NULL),
    [StateType.S_BOSS_STND]: s('boss', 0, 10, A_Look, StateType.S_BOSS_STND2),
    [StateType.S_BOSS_STND2]: s('boss', 1, 10, A_Look, StateType.S_BOSS_STND),
    [StateType.S_BOSS_RUN1]: s('boss', 0, 3, A_Chase, StateType.S_BOSS_RUN2),
    [StateType.S_BOSS_RUN2]: s('boss', 0, 3, A_Chase, StateType.S_BOSS_RUN3),
    [StateType.S_BOSS_RUN3]: s('boss', 1, 3, A_Chase, StateType.S_BOSS_RUN4),
    [StateType.S_BOSS_RUN4]: s('boss', 1, 3, A_Chase, StateType.S_BOSS_RUN5),
    [StateType.S_BOSS_RUN5]: s('boss', 2, 3, A_Chase, StateType.S_BOSS_RUN6),
    [StateType.S_BOSS_RUN6]: s('boss', 2, 3, A_Chase, StateType.S_BOSS_RUN7),
    [StateType.S_BOSS_RUN7]: s('boss', 3, 3, A_Chase, StateType.S_BOSS_RUN8),
    [StateType.S_BOSS_RUN8]: s('boss', 3, 3, A_Chase, StateType.S_BOSS_RUN1),
    [StateType.S_BOSS_ATK1]: s('boss', 4, 8, A_FaceTarget, StateType.S_BOSS_ATK2),
    [StateType.S_BOSS_ATK2]: s('boss', 5, 8, A_FaceTarget, StateType.S_BOSS_ATK3),
    [StateType.S_BOSS_ATK3]: s('boss', 6, 8, A_BruisAttack, StateType.S_BOSS_RUN1),
    [StateType.S_BOSS_PAIN]: s('boss', 7, 2, undefined, StateType.S_BOSS_PAIN2),
    [StateType.S_BOSS_PAIN2]: s('boss', 7, 2, A_Pain, StateType.S_BOSS_RUN1),
    [StateType.S_BOSS_DIE1]: s('boss', 8, 8, undefined, StateType.S_BOSS_DIE2),
    [StateType.S_BOSS_DIE2]: s('boss', 9, 8, A_Scream, StateType.S_BOSS_DIE3),
    [StateType.S_BOSS_DIE3]: s('boss', 10, 8, undefined, StateType.S_BOSS_DIE4),
    [StateType.S_BOSS_DIE4]: s('boss', 11, 8, A_Fall, StateType.S_BOSS_DIE5),
    [StateType.S_BOSS_DIE5]: s('boss', 12, 8, undefined, StateType.S_BOSS_DIE6),
    [StateType.S_BOSS_DIE6]: s('boss', 13, 8, undefined, StateType.S_BOSS_DIE7),
    [StateType.S_BOSS_DIE7]: s('boss', 14, -1, A_BossDeath, StateType.S_NULL),
    [StateType.S_BOSS_RAISE1]: s('boss', 14, 8, undefined, StateType.S_BOSS_RAISE2),
    [StateType.S_BOSS_RAISE2]: s('boss', 13, 8, undefined, StateType.S_BOSS_RAISE3),
    [StateType.S_BOSS_RAISE3]: s('boss', 12, 8, undefined, StateType.S_BOSS_RAISE4),
    [StateType.S_BOSS_RAISE4]: s('boss', 11, 8, undefined, StateType.S_BOSS_RAISE5),
    [StateType.S_BOSS_RAISE5]: s('boss', 10, 8, undefined, StateType.S_BOSS_RAISE6),
    [StateType.S_BOSS_RAISE6]: s('boss', 9, 8, undefined, StateType.S_BOSS_RAISE7),
    [StateType.S_BOSS_RAISE7]: s('boss', 8, 8, undefined, StateType.S_BOSS_RUN1),
    [StateType.S_BOS2_STND]: s('bos2', 0, 10, A_Look, StateType.S_BOS2_STND2),
    [StateType.S_BOS2_STND2]: s('bos2', 1, 10, A_Look, StateType.S_BOS2_STND),
    [StateType.S_BOS2_RUN1]: s('bos2', 0, 3, A_Chase, StateType.S_BOS2_RUN2),
    [StateType.S_BOS2_RUN2]: s('bos2', 0, 3, A_Chase, StateType.S_BOS2_RUN3),
    [StateType.S_BOS2_RUN3]: s('bos2', 1, 3, A_Chase, StateType.S_BOS2_RUN4),
    [StateType.S_BOS2_RUN4]: s('bos2', 1, 3, A_Chase, StateType.S_BOS2_RUN5),
    [StateType.S_BOS2_RUN5]: s('bos2', 2, 3, A_Chase, StateType.S_BOS2_RUN6),
    [StateType.S_BOS2_RUN6]: s('bos2', 2, 3, A_Chase, StateType.S_BOS2_RUN7),
    [StateType.S_BOS2_RUN7]: s('bos2', 3, 3, A_Chase, StateType.S_BOS2_RUN8),
    [StateType.S_BOS2_RUN8]: s('bos2', 3, 3, A_Chase, StateType.S_BOS2_RUN1),
    [StateType.S_BOS2_ATK1]: s('bos2', 4, 8, A_FaceTarget, StateType.S_BOS2_ATK2),
    [StateType.S_BOS2_ATK2]: s('bos2', 5, 8, A_FaceTarget, StateType.S_BOS2_ATK3),
    [StateType.S_BOS2_ATK3]: s('bos2', 6, 8, A_BruisAttack, StateType.S_BOS2_RUN1),
    [StateType.S_BOS2_PAIN]: s('bos2', 7, 2, undefined, StateType.S_BOS2_PAIN2),
    [StateType.S_BOS2_PAIN2]: s('bos2', 7, 2, A_Pain, StateType.S_BOS2_RUN1),
    [StateType.S_BOS2_DIE1]: s('bos2', 8, 8, undefined, StateType.S_BOS2_DIE2),
    [StateType.S_BOS2_DIE2]: s('bos2', 9, 8, A_Scream, StateType.S_BOS2_DIE3),
    [StateType.S_BOS2_DIE3]: s('bos2', 10, 8, undefined, StateType.S_BOS2_DIE4),
    [StateType.S_BOS2_DIE4]: s('bos2', 11, 8, A_Fall, StateType.S_BOS2_DIE5),
    [StateType.S_BOS2_DIE5]: s('bos2', 12, 8, undefined, StateType.S_BOS2_DIE6),
    [StateType.S_BOS2_DIE6]: s('bos2', 13, 8, undefined, StateType.S_BOS2_DIE7),
    [StateType.S_BOS2_DIE7]: s('bos2', 14, -1, undefined, StateType.S_NULL),
    [StateType.S_BOS2_RAISE1]: s('bos2', 14, 8, undefined, StateType.S_BOS2_RAISE2),
    [StateType.S_BOS2_RAISE2]: s('bos2', 13, 8, undefined, StateType.S_BOS2_RAISE3),
    [StateType.S_BOS2_RAISE3]: s('bos2', 12, 8, undefined, StateType.S_BOS2_RAISE4),
    [StateType.S_BOS2_RAISE4]: s('bos2', 11, 8, undefined, StateType.S_BOS2_RAISE5),
    [StateType.S_BOS2_RAISE5]: s('bos2', 10, 8, undefined, StateType.S_BOS2_RAISE6),
    [StateType.S_BOS2_RAISE6]: s('bos2', 9, 8, undefined, StateType.S_BOS2_RAISE7),
    [StateType.S_BOS2_RAISE7]: s('bos2', 8, 8, undefined, StateType.S_BOS2_RUN1),
    [StateType.S_SKULL_STND]: s('skul', 32768, 10, A_Look, StateType.S_SKULL_STND2),
    [StateType.S_SKULL_STND2]: s('skul', 32769, 10, A_Look, StateType.S_SKULL_STND),
    [StateType.S_SKULL_RUN1]: s('skul', 32768, 6, A_Chase, StateType.S_SKULL_RUN2),
    [StateType.S_SKULL_RUN2]: s('skul', 32769, 6, A_Chase, StateType.S_SKULL_RUN1),
    [StateType.S_SKULL_ATK1]: s('skul', 32770, 10, A_FaceTarget, StateType.S_SKULL_ATK2),
    [StateType.S_SKULL_ATK2]: s('skul', 32771, 4, A_SkullAttack, StateType.S_SKULL_ATK3),
    [StateType.S_SKULL_ATK3]: s('skul', 32770, 4, undefined, StateType.S_SKULL_ATK4),
    [StateType.S_SKULL_ATK4]: s('skul', 32771, 4, undefined, StateType.S_SKULL_ATK3),
    [StateType.S_SKULL_PAIN]: s('skul', 32772, 3, undefined, StateType.S_SKULL_PAIN2),
    [StateType.S_SKULL_PAIN2]: s('skul', 32772, 3, A_Pain, StateType.S_SKULL_RUN1),
    [StateType.S_SKULL_DIE1]: s('skul', 32773, 6, undefined, StateType.S_SKULL_DIE2),
    [StateType.S_SKULL_DIE2]: s('skul', 32774, 6, A_Scream, StateType.S_SKULL_DIE3),
    [StateType.S_SKULL_DIE3]: s('skul', 32775, 6, undefined, StateType.S_SKULL_DIE4),
    [StateType.S_SKULL_DIE4]: s('skul', 32776, 6, A_Fall, StateType.S_SKULL_DIE5),
    [StateType.S_SKULL_DIE5]: s('skul', 9, 6, undefined, StateType.S_SKULL_DIE6),
    [StateType.S_SKULL_DIE6]: s('skul', 10, 6, undefined, StateType.S_NULL),
    [StateType.S_SPID_STND]: s('spid', 0, 10, A_Look, StateType.S_SPID_STND2),
    [StateType.S_SPID_STND2]: s('spid', 1, 10, A_Look, StateType.S_SPID_STND),
    [StateType.S_SPID_RUN1]: s('spid', 0, 3, A_Metal, StateType.S_SPID_RUN2),
    [StateType.S_SPID_RUN2]: s('spid', 0, 3, A_Chase, StateType.S_SPID_RUN3),
    [StateType.S_SPID_RUN3]: s('spid', 1, 3, A_Chase, StateType.S_SPID_RUN4),
    [StateType.S_SPID_RUN4]: s('spid', 1, 3, A_Chase, StateType.S_SPID_RUN5),
    [StateType.S_SPID_RUN5]: s('spid', 2, 3, A_Metal, StateType.S_SPID_RUN6),
    [StateType.S_SPID_RUN6]: s('spid', 2, 3, A_Chase, StateType.S_SPID_RUN7),
    [StateType.S_SPID_RUN7]: s('spid', 3, 3, A_Chase, StateType.S_SPID_RUN8),
    [StateType.S_SPID_RUN8]: s('spid', 3, 3, A_Chase, StateType.S_SPID_RUN9),
    [StateType.S_SPID_RUN9]: s('spid', 4, 3, A_Metal, StateType.S_SPID_RUN10),
    [StateType.S_SPID_RUN10]: s('spid', 4, 3, A_Chase, StateType.S_SPID_RUN11),
    [StateType.S_SPID_RUN11]: s('spid', 5, 3, A_Chase, StateType.S_SPID_RUN12),
    [StateType.S_SPID_RUN12]: s('spid', 5, 3, A_Chase, StateType.S_SPID_RUN1),
    [StateType.S_SPID_ATK1]: s('spid', 32768, 20, A_FaceTarget, StateType.S_SPID_ATK2),
    [StateType.S_SPID_ATK2]: s('spid', 32774, 4, A_SPosAttack, StateType.S_SPID_ATK3),
    [StateType.S_SPID_ATK3]: s('spid', 32775, 4, A_SPosAttack, StateType.S_SPID_ATK4),
    [StateType.S_SPID_ATK4]: s('spid', 32775, 1, A_SpidRefire, StateType.S_SPID_ATK2),
    [StateType.S_SPID_PAIN]: s('spid', 8, 3, undefined, StateType.S_SPID_PAIN2),
    [StateType.S_SPID_PAIN2]: s('spid', 8, 3, A_Pain, StateType.S_SPID_RUN1),
    [StateType.S_SPID_DIE1]: s('spid', 9, 20, A_Scream, StateType.S_SPID_DIE2),
    [StateType.S_SPID_DIE2]: s('spid', 10, 10, A_Fall, StateType.S_SPID_DIE3),
    [StateType.S_SPID_DIE3]: s('spid', 11, 10, undefined, StateType.S_SPID_DIE4),
    [StateType.S_SPID_DIE4]: s('spid', 12, 10, undefined, StateType.S_SPID_DIE5),
    [StateType.S_SPID_DIE5]: s('spid', 13, 10, undefined, StateType.S_SPID_DIE6),
    [StateType.S_SPID_DIE6]: s('spid', 14, 10, undefined, StateType.S_SPID_DIE7),
    [StateType.S_SPID_DIE7]: s('spid', 15, 10, undefined, StateType.S_SPID_DIE8),
    [StateType.S_SPID_DIE8]: s('spid', 16, 10, undefined, StateType.S_SPID_DIE9),
    [StateType.S_SPID_DIE9]: s('spid', 17, 10, undefined, StateType.S_SPID_DIE10),
    [StateType.S_SPID_DIE10]: s('spid', 18, 30, undefined, StateType.S_SPID_DIE11),
    [StateType.S_SPID_DIE11]: s('spid', 18, -1, A_BossDeath, StateType.S_NULL),
    [StateType.S_BSPI_STND]: s('bspi', 0, 10, A_Look, StateType.S_BSPI_STND2),
    [StateType.S_BSPI_STND2]: s('bspi', 1, 10, A_Look, StateType.S_BSPI_STND),
    [StateType.S_BSPI_SIGHT]: s('bspi', 0, 20, undefined, StateType.S_BSPI_RUN1),
    [StateType.S_BSPI_RUN1]: s('bspi', 0, 3, A_BabyMetal, StateType.S_BSPI_RUN2),
    [StateType.S_BSPI_RUN2]: s('bspi', 0, 3, A_Chase, StateType.S_BSPI_RUN3),
    [StateType.S_BSPI_RUN3]: s('bspi', 1, 3, A_Chase, StateType.S_BSPI_RUN4),
    [StateType.S_BSPI_RUN4]: s('bspi', 1, 3, A_Chase, StateType.S_BSPI_RUN5),
    [StateType.S_BSPI_RUN5]: s('bspi', 2, 3, A_Chase, StateType.S_BSPI_RUN6),
    [StateType.S_BSPI_RUN6]: s('bspi', 2, 3, A_Chase, StateType.S_BSPI_RUN7),
    [StateType.S_BSPI_RUN7]: s('bspi', 3, 3, A_BabyMetal, StateType.S_BSPI_RUN8),
    [StateType.S_BSPI_RUN8]: s('bspi', 3, 3, A_Chase, StateType.S_BSPI_RUN9),
    [StateType.S_BSPI_RUN9]: s('bspi', 4, 3, A_Chase, StateType.S_BSPI_RUN10),
    [StateType.S_BSPI_RUN10]: s('bspi', 4, 3, A_Chase, StateType.S_BSPI_RUN11),
    [StateType.S_BSPI_RUN11]: s('bspi', 5, 3, A_Chase, StateType.S_BSPI_RUN12),
    [StateType.S_BSPI_RUN12]: s('bspi', 5, 3, A_Chase, StateType.S_BSPI_RUN1),
    [StateType.S_BSPI_ATK1]: s('bspi', 32768, 20, A_FaceTarget, StateType.S_BSPI_ATK2),
    [StateType.S_BSPI_ATK2]: s('bspi', 32774, 4, A_BspiAttack, StateType.S_BSPI_ATK3),
    [StateType.S_BSPI_ATK3]: s('bspi', 32775, 4, undefined, StateType.S_BSPI_ATK4),
    [StateType.S_BSPI_ATK4]: s('bspi', 32775, 1, A_SpidRefire, StateType.S_BSPI_ATK2),
    [StateType.S_BSPI_PAIN]: s('bspi', 8, 3, undefined, StateType.S_BSPI_PAIN2),
    [StateType.S_BSPI_PAIN2]: s('bspi', 8, 3, A_Pain, StateType.S_BSPI_RUN1),
    [StateType.S_BSPI_DIE1]: s('bspi', 9, 20, A_Scream, StateType.S_BSPI_DIE2),
    [StateType.S_BSPI_DIE2]: s('bspi', 10, 7, A_Fall, StateType.S_BSPI_DIE3),
    [StateType.S_BSPI_DIE3]: s('bspi', 11, 7, undefined, StateType.S_BSPI_DIE4),
    [StateType.S_BSPI_DIE4]: s('bspi', 12, 7, undefined, StateType.S_BSPI_DIE5),
    [StateType.S_BSPI_DIE5]: s('bspi', 13, 7, undefined, StateType.S_BSPI_DIE6),
    [StateType.S_BSPI_DIE6]: s('bspi', 14, 7, undefined, StateType.S_BSPI_DIE7),
    [StateType.S_BSPI_DIE7]: s('bspi', 15, -1, A_BossDeath, StateType.S_NULL),
    [StateType.S_BSPI_RAISE1]: s('bspi', 15, 5, undefined, StateType.S_BSPI_RAISE2),
    [StateType.S_BSPI_RAISE2]: s('bspi', 14, 5, undefined, StateType.S_BSPI_RAISE3),
    [StateType.S_BSPI_RAISE3]: s('bspi', 13, 5, undefined, StateType.S_BSPI_RAISE4),
    [StateType.S_BSPI_RAISE4]: s('bspi', 12, 5, undefined, StateType.S_BSPI_RAISE5),
    [StateType.S_BSPI_RAISE5]: s('bspi', 11, 5, undefined, StateType.S_BSPI_RAISE6),
    [StateType.S_BSPI_RAISE6]: s('bspi', 10, 5, undefined, StateType.S_BSPI_RAISE7),
    [StateType.S_BSPI_RAISE7]: s('bspi', 9, 5, undefined, StateType.S_BSPI_RUN1),
    [StateType.S_ARACH_PLAZ]: s('apls', 32768, 5, undefined, StateType.S_ARACH_PLAZ2),
    [StateType.S_ARACH_PLAZ2]: s('apls', 32769, 5, undefined, StateType.S_ARACH_PLAZ),
    [StateType.S_ARACH_PLEX]: s('apbx', 32768, 5, undefined, StateType.S_ARACH_PLEX2),
    [StateType.S_ARACH_PLEX2]: s('apbx', 32769, 5, undefined, StateType.S_ARACH_PLEX3),
    [StateType.S_ARACH_PLEX3]: s('apbx', 32770, 5, undefined, StateType.S_ARACH_PLEX4),
    [StateType.S_ARACH_PLEX4]: s('apbx', 32771, 5, undefined, StateType.S_ARACH_PLEX5),
    [StateType.S_ARACH_PLEX5]: s('apbx', 32772, 5, undefined, StateType.S_NULL),
    [StateType.S_CYBER_STND]: s('cybr', 0, 10, A_Look, StateType.S_CYBER_STND2),
    [StateType.S_CYBER_STND2]: s('cybr', 1, 10, A_Look, StateType.S_CYBER_STND),
    [StateType.S_CYBER_RUN1]: s('cybr', 0, 3, A_Hoof, StateType.S_CYBER_RUN2),
    [StateType.S_CYBER_RUN2]: s('cybr', 0, 3, A_Chase, StateType.S_CYBER_RUN3),
    [StateType.S_CYBER_RUN3]: s('cybr', 1, 3, A_Chase, StateType.S_CYBER_RUN4),
    [StateType.S_CYBER_RUN4]: s('cybr', 1, 3, A_Chase, StateType.S_CYBER_RUN5),
    [StateType.S_CYBER_RUN5]: s('cybr', 2, 3, A_Chase, StateType.S_CYBER_RUN6),
    [StateType.S_CYBER_RUN6]: s('cybr', 2, 3, A_Chase, StateType.S_CYBER_RUN7),
    [StateType.S_CYBER_RUN7]: s('cybr', 3, 3, A_Metal, StateType.S_CYBER_RUN8),
    [StateType.S_CYBER_RUN8]: s('cybr', 3, 3, A_Chase, StateType.S_CYBER_RUN1),
    [StateType.S_CYBER_ATK1]: s('cybr', 4, 6, A_FaceTarget, StateType.S_CYBER_ATK2),
    [StateType.S_CYBER_ATK2]: s('cybr', 5, 12, A_CyberAttack, StateType.S_CYBER_ATK3),
    [StateType.S_CYBER_ATK3]: s('cybr', 4, 12, A_FaceTarget, StateType.S_CYBER_ATK4),
    [StateType.S_CYBER_ATK4]: s('cybr', 5, 12, A_CyberAttack, StateType.S_CYBER_ATK5),
    [StateType.S_CYBER_ATK5]: s('cybr', 4, 12, A_FaceTarget, StateType.S_CYBER_ATK6),
    [StateType.S_CYBER_ATK6]: s('cybr', 5, 12, A_CyberAttack, StateType.S_CYBER_RUN1),
    [StateType.S_CYBER_PAIN]: s('cybr', 6, 10, A_Pain, StateType.S_CYBER_RUN1),
    [StateType.S_CYBER_DIE1]: s('cybr', 7, 10, undefined, StateType.S_CYBER_DIE2),
    [StateType.S_CYBER_DIE2]: s('cybr', 8, 10, A_Scream, StateType.S_CYBER_DIE3),
    [StateType.S_CYBER_DIE3]: s('cybr', 9, 10, undefined, StateType.S_CYBER_DIE4),
    [StateType.S_CYBER_DIE4]: s('cybr', 10, 10, undefined, StateType.S_CYBER_DIE5),
    [StateType.S_CYBER_DIE5]: s('cybr', 11, 10, undefined, StateType.S_CYBER_DIE6),
    [StateType.S_CYBER_DIE6]: s('cybr', 12, 10, A_Fall, StateType.S_CYBER_DIE7),
    [StateType.S_CYBER_DIE7]: s('cybr', 13, 10, undefined, StateType.S_CYBER_DIE8),
    [StateType.S_CYBER_DIE8]: s('cybr', 14, 10, undefined, StateType.S_CYBER_DIE9),
    [StateType.S_CYBER_DIE9]: s('cybr', 15, 30, undefined, StateType.S_CYBER_DIE10),
    [StateType.S_CYBER_DIE10]: s('cybr', 15, -1, A_BossDeath, StateType.S_NULL),
    [StateType.S_PAIN_STND]: s('pain', 0, 10, A_Look, StateType.S_PAIN_STND),
    [StateType.S_PAIN_RUN1]: s('pain', 0, 3, A_Chase, StateType.S_PAIN_RUN2),
    [StateType.S_PAIN_RUN2]: s('pain', 0, 3, A_Chase, StateType.S_PAIN_RUN3),
    [StateType.S_PAIN_RUN3]: s('pain', 1, 3, A_Chase, StateType.S_PAIN_RUN4),
    [StateType.S_PAIN_RUN4]: s('pain', 1, 3, A_Chase, StateType.S_PAIN_RUN5),
    [StateType.S_PAIN_RUN5]: s('pain', 2, 3, A_Chase, StateType.S_PAIN_RUN6),
    [StateType.S_PAIN_RUN6]: s('pain', 2, 3, A_Chase, StateType.S_PAIN_RUN1),
    [StateType.S_PAIN_ATK1]: s('pain', 3, 5, A_FaceTarget, StateType.S_PAIN_ATK2),
    [StateType.S_PAIN_ATK2]: s('pain', 4, 5, A_FaceTarget, StateType.S_PAIN_ATK3),
    [StateType.S_PAIN_ATK3]: s('pain', 32773, 5, A_FaceTarget, StateType.S_PAIN_ATK4),
    [StateType.S_PAIN_ATK4]: s('pain', 32773, 0, A_PainAttack, StateType.S_PAIN_RUN1),
    [StateType.S_PAIN_PAIN]: s('pain', 6, 6, undefined, StateType.S_PAIN_PAIN2),
    [StateType.S_PAIN_PAIN2]: s('pain', 6, 6, A_Pain, StateType.S_PAIN_RUN1),
    [StateType.S_PAIN_DIE1]: s('pain', 32775, 8, undefined, StateType.S_PAIN_DIE2),
    [StateType.S_PAIN_DIE2]: s('pain', 32776, 8, A_Scream, StateType.S_PAIN_DIE3),
    [StateType.S_PAIN_DIE3]: s('pain', 32777, 8, undefined, StateType.S_PAIN_DIE4),
    [StateType.S_PAIN_DIE4]: s('pain', 32778, 8, undefined, StateType.S_PAIN_DIE5),
    [StateType.S_PAIN_DIE5]: s('pain', 32779, 8, A_PainDie, StateType.S_PAIN_DIE6),
    [StateType.S_PAIN_DIE6]: s('pain', 32780, 8, undefined, StateType.S_NULL),
    [StateType.S_PAIN_RAISE1]: s('pain', 12, 8, undefined, StateType.S_PAIN_RAISE2),
    [StateType.S_PAIN_RAISE2]: s('pain', 11, 8, undefined, StateType.S_PAIN_RAISE3),
    [StateType.S_PAIN_RAISE3]: s('pain', 10, 8, undefined, StateType.S_PAIN_RAISE4),
    [StateType.S_PAIN_RAISE4]: s('pain', 9, 8, undefined, StateType.S_PAIN_RAISE5),
    [StateType.S_PAIN_RAISE5]: s('pain', 8, 8, undefined, StateType.S_PAIN_RAISE6),
    [StateType.S_PAIN_RAISE6]: s('pain', 7, 8, undefined, StateType.S_PAIN_RUN1),
    [StateType.S_SSWV_STND]: s('sswv', 0, 10, A_Look, StateType.S_SSWV_STND2),
    [StateType.S_SSWV_STND2]: s('sswv', 1, 10, A_Look, StateType.S_SSWV_STND),
    [StateType.S_SSWV_RUN1]: s('sswv', 0, 3, A_Chase, StateType.S_SSWV_RUN2),
    [StateType.S_SSWV_RUN2]: s('sswv', 0, 3, A_Chase, StateType.S_SSWV_RUN3),
    [StateType.S_SSWV_RUN3]: s('sswv', 1, 3, A_Chase, StateType.S_SSWV_RUN4),
    [StateType.S_SSWV_RUN4]: s('sswv', 1, 3, A_Chase, StateType.S_SSWV_RUN5),
    [StateType.S_SSWV_RUN5]: s('sswv', 2, 3, A_Chase, StateType.S_SSWV_RUN6),
    [StateType.S_SSWV_RUN6]: s('sswv', 2, 3, A_Chase, StateType.S_SSWV_RUN7),
    [StateType.S_SSWV_RUN7]: s('sswv', 3, 3, A_Chase, StateType.S_SSWV_RUN8),
    [StateType.S_SSWV_RUN8]: s('sswv', 3, 3, A_Chase, StateType.S_SSWV_RUN1),
    [StateType.S_SSWV_ATK1]: s('sswv', 4, 10, A_FaceTarget, StateType.S_SSWV_ATK2),
    [StateType.S_SSWV_ATK2]: s('sswv', 5, 10, A_FaceTarget, StateType.S_SSWV_ATK3),
    [StateType.S_SSWV_ATK3]: s('sswv', 32774, 4, A_CPosAttack, StateType.S_SSWV_ATK4),
    [StateType.S_SSWV_ATK4]: s('sswv', 5, 6, A_FaceTarget, StateType.S_SSWV_ATK5),
    [StateType.S_SSWV_ATK5]: s('sswv', 32774, 4, A_CPosAttack, StateType.S_SSWV_ATK6),
    [StateType.S_SSWV_ATK6]: s('sswv', 5, 1, A_CPosRefire, StateType.S_SSWV_ATK2),
    [StateType.S_SSWV_PAIN]: s('sswv', 7, 3, undefined, StateType.S_SSWV_PAIN2),
    [StateType.S_SSWV_PAIN2]: s('sswv', 7, 3, A_Pain, StateType.S_SSWV_RUN1),
    [StateType.S_SSWV_DIE1]: s('sswv', 8, 5, undefined, StateType.S_SSWV_DIE2),
    [StateType.S_SSWV_DIE2]: s('sswv', 9, 5, A_Scream, StateType.S_SSWV_DIE3),
    [StateType.S_SSWV_DIE3]: s('sswv', 10, 5, A_Fall, StateType.S_SSWV_DIE4),
    [StateType.S_SSWV_DIE4]: s('sswv', 11, 5, undefined, StateType.S_SSWV_DIE5),
    [StateType.S_SSWV_DIE5]: s('sswv', 12, -1, undefined, StateType.S_NULL),
    [StateType.S_SSWV_XDIE1]: s('sswv', 13, 5, undefined, StateType.S_SSWV_XDIE2),
    [StateType.S_SSWV_XDIE2]: s('sswv', 14, 5, A_XScream, StateType.S_SSWV_XDIE3),
    [StateType.S_SSWV_XDIE3]: s('sswv', 15, 5, A_Fall, StateType.S_SSWV_XDIE4),
    [StateType.S_SSWV_XDIE4]: s('sswv', 16, 5, undefined, StateType.S_SSWV_XDIE5),
    [StateType.S_SSWV_XDIE5]: s('sswv', 17, 5, undefined, StateType.S_SSWV_XDIE6),
    [StateType.S_SSWV_XDIE6]: s('sswv', 18, 5, undefined, StateType.S_SSWV_XDIE7),
    [StateType.S_SSWV_XDIE7]: s('sswv', 19, 5, undefined, StateType.S_SSWV_XDIE8),
    [StateType.S_SSWV_XDIE8]: s('sswv', 20, 5, undefined, StateType.S_SSWV_XDIE9),
    [StateType.S_SSWV_XDIE9]: s('sswv', 21, -1, undefined, StateType.S_NULL),
    [StateType.S_SSWV_RAISE1]: s('sswv', 12, 5, undefined, StateType.S_SSWV_RAISE2),
    [StateType.S_SSWV_RAISE2]: s('sswv', 11, 5, undefined, StateType.S_SSWV_RAISE3),
    [StateType.S_SSWV_RAISE3]: s('sswv', 10, 5, undefined, StateType.S_SSWV_RAISE4),
    [StateType.S_SSWV_RAISE4]: s('sswv', 9, 5, undefined, StateType.S_SSWV_RAISE5),
    [StateType.S_SSWV_RAISE5]: s('sswv', 8, 5, undefined, StateType.S_SSWV_RUN1),
    [StateType.S_KEENSTND]: s('keen', 0, -1, undefined, StateType.S_KEENSTND),
    [StateType.S_COMMKEEN]: s('keen', 0, 6, undefined, StateType.S_COMMKEEN2),
    [StateType.S_COMMKEEN2]: s('keen', 1, 6, undefined, StateType.S_COMMKEEN3),
    [StateType.S_COMMKEEN3]: s('keen', 2, 6, A_Scream, StateType.S_COMMKEEN4),
    [StateType.S_COMMKEEN4]: s('keen', 3, 6, undefined, StateType.S_COMMKEEN5),
    [StateType.S_COMMKEEN5]: s('keen', 4, 6, undefined, StateType.S_COMMKEEN6),
    [StateType.S_COMMKEEN6]: s('keen', 5, 6, undefined, StateType.S_COMMKEEN7),
    [StateType.S_COMMKEEN7]: s('keen', 6, 6, undefined, StateType.S_COMMKEEN8),
    [StateType.S_COMMKEEN8]: s('keen', 7, 6, undefined, StateType.S_COMMKEEN9),
    [StateType.S_COMMKEEN9]: s('keen', 8, 6, undefined, StateType.S_COMMKEEN10),
    [StateType.S_COMMKEEN10]: s('keen', 9, 6, undefined, StateType.S_COMMKEEN11),
    [StateType.S_COMMKEEN11]: s('keen', 10, 6, A_KeenDie, StateType.S_COMMKEEN12),
    [StateType.S_COMMKEEN12]: s('keen', 11, -1, undefined, StateType.S_NULL),
    [StateType.S_KEENPAIN]: s('keen', 12, 4, undefined, StateType.S_KEENPAIN2),
    [StateType.S_KEENPAIN2]: s('keen', 12, 8, A_Pain, StateType.S_KEENSTND),
    [StateType.S_BRAIN]: s('bbrn', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_BRAIN_PAIN]: s('bbrn', 1, 36, A_BrainPain, StateType.S_BRAIN),
    [StateType.S_BRAIN_DIE1]: s('bbrn', 0, 100, A_BrainScream, StateType.S_BRAIN_DIE2),
    [StateType.S_BRAIN_DIE2]: s('bbrn', 0, 10, undefined, StateType.S_BRAIN_DIE3),
    [StateType.S_BRAIN_DIE3]: s('bbrn', 0, 10, undefined, StateType.S_BRAIN_DIE4),
    [StateType.S_BRAIN_DIE4]: s('bbrn', 0, -1, A_BrainDie, StateType.S_NULL),
    [StateType.S_BRAINEYE]: s('sswv', 0, 10, A_Look, StateType.S_BRAINEYE),
    [StateType.S_BRAINEYESEE]: s('sswv', 0, 181, A_BrainAwake, StateType.S_BRAINEYE1),
    [StateType.S_BRAINEYE1]: s('sswv', 0, 150, A_BrainSpit, StateType.S_BRAINEYE1),
    [StateType.S_SPAWN1]: s('bosf', 32768, 3, A_SpawnSound, StateType.S_SPAWN2),
    [StateType.S_SPAWN2]: s('bosf', 32769, 3, A_SpawnFly, StateType.S_SPAWN3),
    [StateType.S_SPAWN3]: s('bosf', 32770, 3, A_SpawnFly, StateType.S_SPAWN4),
    [StateType.S_SPAWN4]: s('bosf', 32771, 3, A_SpawnFly, StateType.S_SPAWN1),
    [StateType.S_SPAWNFIRE1]: s('fire', 32768, 4, A_Fire, StateType.S_SPAWNFIRE2),
    [StateType.S_SPAWNFIRE2]: s('fire', 32769, 4, A_Fire, StateType.S_SPAWNFIRE3),
    [StateType.S_SPAWNFIRE3]: s('fire', 32770, 4, A_Fire, StateType.S_SPAWNFIRE4),
    [StateType.S_SPAWNFIRE4]: s('fire', 32771, 4, A_Fire, StateType.S_SPAWNFIRE5),
    [StateType.S_SPAWNFIRE5]: s('fire', 32772, 4, A_Fire, StateType.S_SPAWNFIRE6),
    [StateType.S_SPAWNFIRE6]: s('fire', 32773, 4, A_Fire, StateType.S_SPAWNFIRE7),
    [StateType.S_SPAWNFIRE7]: s('fire', 32774, 4, A_Fire, StateType.S_SPAWNFIRE8),
    [StateType.S_SPAWNFIRE8]: s('fire', 32775, 4, A_Fire, StateType.S_NULL),
    [StateType.S_BRAINEXPLODE1]: s('misl', 32769, 10, undefined, StateType.S_BRAINEXPLODE2),
    [StateType.S_BRAINEXPLODE2]: s('misl', 32770, 10, undefined, StateType.S_BRAINEXPLODE3),
    [StateType.S_BRAINEXPLODE3]: s('misl', 32771, 10, A_BrainExplode, StateType.S_NULL),
    [StateType.S_ARM1]: s('arm1', 0, 6, undefined, StateType.S_ARM1A),
    [StateType.S_ARM1A]: s('arm1', 32769, 7, undefined, StateType.S_ARM1),
    [StateType.S_ARM2]: s('arm2', 0, 6, undefined, StateType.S_ARM2A),
    [StateType.S_ARM2A]: s('arm2', 32769, 6, undefined, StateType.S_ARM2),
    [StateType.S_BAR1]: s('bar1', 0, 6, undefined, StateType.S_BAR2),
    [StateType.S_BAR2]: s('bar1', 1, 6, undefined, StateType.S_BAR1),
    [StateType.S_BEXP]: s('bexp', 32768, 5, undefined, StateType.S_BEXP2),
    [StateType.S_BEXP2]: s('bexp', 32769, 5, A_Scream, StateType.S_BEXP3),
    [StateType.S_BEXP3]: s('bexp', 32770, 5, undefined, StateType.S_BEXP4),
    [StateType.S_BEXP4]: s('bexp', 32771, 10, A_Explode, StateType.S_BEXP5),
    [StateType.S_BEXP5]: s('bexp', 32772, 10, undefined, StateType.S_NULL),
    [StateType.S_BBAR1]: s('fcan', 32768, 4, undefined, StateType.S_BBAR2),
    [StateType.S_BBAR2]: s('fcan', 32769, 4, undefined, StateType.S_BBAR3),
    [StateType.S_BBAR3]: s('fcan', 32770, 4, undefined, StateType.S_BBAR1),
    [StateType.S_BON1]: s('bon1', 0, 6, undefined, StateType.S_BON1A),
    [StateType.S_BON1A]: s('bon1', 1, 6, undefined, StateType.S_BON1B),
    [StateType.S_BON1B]: s('bon1', 2, 6, undefined, StateType.S_BON1C),
    [StateType.S_BON1C]: s('bon1', 3, 6, undefined, StateType.S_BON1D),
    [StateType.S_BON1D]: s('bon1', 2, 6, undefined, StateType.S_BON1E),
    [StateType.S_BON1E]: s('bon1', 1, 6, undefined, StateType.S_BON1),
    [StateType.S_BON2]: s('bon2', 0, 6, undefined, StateType.S_BON2A),
    [StateType.S_BON2A]: s('bon2', 1, 6, undefined, StateType.S_BON2B),
    [StateType.S_BON2B]: s('bon2', 2, 6, undefined, StateType.S_BON2C),
    [StateType.S_BON2C]: s('bon2', 3, 6, undefined, StateType.S_BON2D),
    [StateType.S_BON2D]: s('bon2', 2, 6, undefined, StateType.S_BON2E),
    [StateType.S_BON2E]: s('bon2', 1, 6, undefined, StateType.S_BON2),
    [StateType.S_BKEY]: s('bkey', 0, 10, undefined, StateType.S_BKEY2),
    [StateType.S_BKEY2]: s('bkey', 32769, 10, undefined, StateType.S_BKEY),
    [StateType.S_RKEY]: s('rkey', 0, 10, undefined, StateType.S_RKEY2),
    [StateType.S_RKEY2]: s('rkey', 32769, 10, undefined, StateType.S_RKEY),
    [StateType.S_YKEY]: s('ykey', 0, 10, undefined, StateType.S_YKEY2),
    [StateType.S_YKEY2]: s('ykey', 32769, 10, undefined, StateType.S_YKEY),
    [StateType.S_BSKULL]: s('bsku', 0, 10, undefined, StateType.S_BSKULL2),
    [StateType.S_BSKULL2]: s('bsku', 32769, 10, undefined, StateType.S_BSKULL),
    [StateType.S_RSKULL]: s('rsku', 0, 10, undefined, StateType.S_RSKULL2),
    [StateType.S_RSKULL2]: s('rsku', 32769, 10, undefined, StateType.S_RSKULL),
    [StateType.S_YSKULL]: s('ysku', 0, 10, undefined, StateType.S_YSKULL2),
    [StateType.S_YSKULL2]: s('ysku', 32769, 10, undefined, StateType.S_YSKULL),
    [StateType.S_STIM]: s('stim', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_MEDI]: s('medi', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_SOUL]: s('soul', 32768, 6, undefined, StateType.S_SOUL2),
    [StateType.S_SOUL2]: s('soul', 32769, 6, undefined, StateType.S_SOUL3),
    [StateType.S_SOUL3]: s('soul', 32770, 6, undefined, StateType.S_SOUL4),
    [StateType.S_SOUL4]: s('soul', 32771, 6, undefined, StateType.S_SOUL5),
    [StateType.S_SOUL5]: s('soul', 32770, 6, undefined, StateType.S_SOUL6),
    [StateType.S_SOUL6]: s('soul', 32769, 6, undefined, StateType.S_SOUL),
    [StateType.S_PINV]: s('pinv', 32768, 6, undefined, StateType.S_PINV2),
    [StateType.S_PINV2]: s('pinv', 32769, 6, undefined, StateType.S_PINV3),
    [StateType.S_PINV3]: s('pinv', 32770, 6, undefined, StateType.S_PINV4),
    [StateType.S_PINV4]: s('pinv', 32771, 6, undefined, StateType.S_PINV),
    [StateType.S_PSTR]: s('pstr', 32768, -1, undefined, StateType.S_NULL),
    [StateType.S_PINS]: s('pins', 32768, 6, undefined, StateType.S_PINS2),
    [StateType.S_PINS2]: s('pins', 32769, 6, undefined, StateType.S_PINS3),
    [StateType.S_PINS3]: s('pins', 32770, 6, undefined, StateType.S_PINS4),
    [StateType.S_PINS4]: s('pins', 32771, 6, undefined, StateType.S_PINS),
    [StateType.S_MEGA]: s('mega', 32768, 6, undefined, StateType.S_MEGA2),
    [StateType.S_MEGA2]: s('mega', 32769, 6, undefined, StateType.S_MEGA3),
    [StateType.S_MEGA3]: s('mega', 32770, 6, undefined, StateType.S_MEGA4),
    [StateType.S_MEGA4]: s('mega', 32771, 6, undefined, StateType.S_MEGA),
    [StateType.S_SUIT]: s('suit', 32768, -1, undefined, StateType.S_NULL),
    [StateType.S_PMAP]: s('pmap', 32768, 6, undefined, StateType.S_PMAP2),
    [StateType.S_PMAP2]: s('pmap', 32769, 6, undefined, StateType.S_PMAP3),
    [StateType.S_PMAP3]: s('pmap', 32770, 6, undefined, StateType.S_PMAP4),
    [StateType.S_PMAP4]: s('pmap', 32771, 6, undefined, StateType.S_PMAP5),
    [StateType.S_PMAP5]: s('pmap', 32770, 6, undefined, StateType.S_PMAP6),
    [StateType.S_PMAP6]: s('pmap', 32769, 6, undefined, StateType.S_PMAP),
    [StateType.S_PVIS]: s('pvis', 32768, 6, undefined, StateType.S_PVIS2),
    [StateType.S_PVIS2]: s('pvis', 1, 6, undefined, StateType.S_PVIS),
    [StateType.S_CLIP]: s('clip', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_AMMO]: s('ammo', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_ROCK]: s('rock', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_BROK]: s('brok', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_CELL]: s('cell', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_CELP]: s('celp', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_SHEL]: s('shel', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_SBOX]: s('sbox', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_BPAK]: s('bpak', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_BFUG]: s('bfug', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_MGUN]: s('mgun', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_CSAW]: s('csaw', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_LAUN]: s('laun', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_PLAS]: s('plas', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_SHOT]: s('shot', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_SHOT2]: s('sgn2', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_COLU]: s('colu', 32768, -1, undefined, StateType.S_NULL),
    [StateType.S_STALAG]: s('smt2', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_BLOODYTWITCH]: s('gor1', 0, 10, undefined, StateType.S_BLOODYTWITCH2),
    [StateType.S_BLOODYTWITCH2]: s('gor1', 1, 15, undefined, StateType.S_BLOODYTWITCH3),
    [StateType.S_BLOODYTWITCH3]: s('gor1', 2, 8, undefined, StateType.S_BLOODYTWITCH4),
    [StateType.S_BLOODYTWITCH4]: s('gor1', 1, 6, undefined, StateType.S_BLOODYTWITCH),
    [StateType.S_DEADTORSO]: s('play', 13, -1, undefined, StateType.S_NULL),
    [StateType.S_DEADBOTTOM]: s('play', 18, -1, undefined, StateType.S_NULL),
    [StateType.S_HEADSONSTICK]: s('pol2', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_GIBS]: s('pol5', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_HEADONASTICK]: s('pol4', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_HEADCANDLES]: s('pol3', 32768, 6, undefined, StateType.S_HEADCANDLES2),
    [StateType.S_HEADCANDLES2]: s('pol3', 32769, 6, undefined, StateType.S_HEADCANDLES),
    [StateType.S_DEADSTICK]: s('pol1', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_LIVESTICK]: s('pol6', 0, 6, undefined, StateType.S_LIVESTICK2),
    [StateType.S_LIVESTICK2]: s('pol6', 1, 8, undefined, StateType.S_LIVESTICK),
    [StateType.S_MEAT2]: s('gor2', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_MEAT3]: s('gor3', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_MEAT4]: s('gor4', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_MEAT5]: s('gor5', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_STALAGTITE]: s('smit', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_TALLGRNCOL]: s('col1', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_SHRTGRNCOL]: s('col2', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_TALLREDCOL]: s('col3', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_SHRTREDCOL]: s('col4', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_CANDLESTIK]: s('cand', 32768, -1, undefined, StateType.S_NULL),
    [StateType.S_CANDELABRA]: s('cbra', 32768, -1, undefined, StateType.S_NULL),
    [StateType.S_SKULLCOL]: s('col6', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_TORCHTREE]: s('tre1', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_BIGTREE]: s('tre2', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_TECHPILLAR]: s('elec', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_EVILEYE]: s('ceye', 32768, 6, undefined, StateType.S_EVILEYE2),
    [StateType.S_EVILEYE2]: s('ceye', 32769, 6, undefined, StateType.S_EVILEYE3),
    [StateType.S_EVILEYE3]: s('ceye', 32770, 6, undefined, StateType.S_EVILEYE4),
    [StateType.S_EVILEYE4]: s('ceye', 32769, 6, undefined, StateType.S_EVILEYE),
    [StateType.S_FLOATSKULL]: s('fsku', 32768, 6, undefined, StateType.S_FLOATSKULL2),
    [StateType.S_FLOATSKULL2]: s('fsku', 32769, 6, undefined, StateType.S_FLOATSKULL3),
    [StateType.S_FLOATSKULL3]: s('fsku', 32770, 6, undefined, StateType.S_FLOATSKULL),
    [StateType.S_HEARTCOL]: s('col5', 0, 14, undefined, StateType.S_HEARTCOL2),
    [StateType.S_HEARTCOL2]: s('col5', 1, 14, undefined, StateType.S_HEARTCOL),
    [StateType.S_BLUETORCH]: s('tblu', 32768, 4, undefined, StateType.S_BLUETORCH2),
    [StateType.S_BLUETORCH2]: s('tblu', 32769, 4, undefined, StateType.S_BLUETORCH3),
    [StateType.S_BLUETORCH3]: s('tblu', 32770, 4, undefined, StateType.S_BLUETORCH4),
    [StateType.S_BLUETORCH4]: s('tblu', 32771, 4, undefined, StateType.S_BLUETORCH),
    [StateType.S_GREENTORCH]: s('tgrn', 32768, 4, undefined, StateType.S_GREENTORCH2),
    [StateType.S_GREENTORCH2]: s('tgrn', 32769, 4, undefined, StateType.S_GREENTORCH3),
    [StateType.S_GREENTORCH3]: s('tgrn', 32770, 4, undefined, StateType.S_GREENTORCH4),
    [StateType.S_GREENTORCH4]: s('tgrn', 32771, 4, undefined, StateType.S_GREENTORCH),
    [StateType.S_REDTORCH]: s('tred', 32768, 4, undefined, StateType.S_REDTORCH2),
    [StateType.S_REDTORCH2]: s('tred', 32769, 4, undefined, StateType.S_REDTORCH3),
    [StateType.S_REDTORCH3]: s('tred', 32770, 4, undefined, StateType.S_REDTORCH4),
    [StateType.S_REDTORCH4]: s('tred', 32771, 4, undefined, StateType.S_REDTORCH),
    [StateType.S_BTORCHSHRT]: s('smbt', 32768, 4, undefined, StateType.S_BTORCHSHRT2),
    [StateType.S_BTORCHSHRT2]: s('smbt', 32769, 4, undefined, StateType.S_BTORCHSHRT3),
    [StateType.S_BTORCHSHRT3]: s('smbt', 32770, 4, undefined, StateType.S_BTORCHSHRT4),
    [StateType.S_BTORCHSHRT4]: s('smbt', 32771, 4, undefined, StateType.S_BTORCHSHRT),
    [StateType.S_GTORCHSHRT]: s('smgt', 32768, 4, undefined, StateType.S_GTORCHSHRT2),
    [StateType.S_GTORCHSHRT2]: s('smgt', 32769, 4, undefined, StateType.S_GTORCHSHRT3),
    [StateType.S_GTORCHSHRT3]: s('smgt', 32770, 4, undefined, StateType.S_GTORCHSHRT4),
    [StateType.S_GTORCHSHRT4]: s('smgt', 32771, 4, undefined, StateType.S_GTORCHSHRT),
    [StateType.S_RTORCHSHRT]: s('smrt', 32768, 4, undefined, StateType.S_RTORCHSHRT2),
    [StateType.S_RTORCHSHRT2]: s('smrt', 32769, 4, undefined, StateType.S_RTORCHSHRT3),
    [StateType.S_RTORCHSHRT3]: s('smrt', 32770, 4, undefined, StateType.S_RTORCHSHRT4),
    [StateType.S_RTORCHSHRT4]: s('smrt', 32771, 4, undefined, StateType.S_RTORCHSHRT),
    [StateType.S_HANGNOGUTS]: s('hdb1', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_HANGBNOBRAIN]: s('hdb2', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_HANGTLOOKDN]: s('hdb3', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_HANGTSKULL]: s('hdb4', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_HANGTLOOKUP]: s('hdb5', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_HANGTNOBRAIN]: s('hdb6', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_COLONGIBS]: s('pob1', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_SMALLPOOL]: s('pob2', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_BRAINSTEM]: s('brs1', 0, -1, undefined, StateType.S_NULL),
    [StateType.S_TECHLAMP]: s('tlmp', 32768, 4, undefined, StateType.S_TECHLAMP2),
    [StateType.S_TECHLAMP2]: s('tlmp', 32769, 4, undefined, StateType.S_TECHLAMP3),
    [StateType.S_TECHLAMP3]: s('tlmp', 32770, 4, undefined, StateType.S_TECHLAMP4),
    [StateType.S_TECHLAMP4]: s('tlmp', 32771, 4, undefined, StateType.S_TECHLAMP),
    [StateType.S_TECH2LAMP]: s('tlp2', 32768, 4, undefined, StateType.S_TECH2LAMP2),
    [StateType.S_TECH2LAMP2]: s('tlp2', 32769, 4, undefined, StateType.S_TECH2LAMP3),
    [StateType.S_TECH2LAMP3]: s('tlp2', 32770, 4, undefined, StateType.S_TECH2LAMP4),
    [StateType.S_TECH2LAMP4]: s('tlp2', 32771, 4, undefined, StateType.S_TECH2LAMP)
} as StateLookupType
