// Built from doom source info.c and following regex find and repalce
// void.*(A_[A-Za-z0-9_]+)\(\);
// export const $1 = (stateful: Stateful): void => {}

import { Stateful } from '../interfaces/State'

export const A_Punch = (stateful: Stateful): void => {}
export const A_ReFire = (stateful: Stateful): void => {}
export const A_FireShotgun = (stateful: Stateful): void => {}
export const A_Light2 = (stateful: Stateful): void => {}
export const A_FireShotgun2 = (stateful: Stateful): void => {}
export const A_CheckReload = (stateful: Stateful): void => {}
export const A_OpenShotgun2 = (stateful: Stateful): void => {}
export const A_LoadShotgun2 = (stateful: Stateful): void => {}
export const A_CloseShotgun2 = (stateful: Stateful): void => {}
export const A_FireCGun = (stateful: Stateful): void => {}
export const A_GunFlash = (stateful: Stateful): void => {}
export const A_FireMissile = (stateful: Stateful): void => {}
export const A_Saw = (stateful: Stateful): void => {}
export const A_FirePlasma = (stateful: Stateful): void => {}
export const A_BFGsound = (stateful: Stateful): void => {}
export const A_FireBFG = (stateful: Stateful): void => {}
export const A_BFGSpray = (stateful: Stateful): void => {}
export const A_Explode = (stateful: Stateful): void => {}
export const A_Pain = (stateful: Stateful): void => {}
export const A_PlayerScream = (stateful: Stateful): void => {}
export const A_Fall = (stateful: Stateful): void => {}
export const A_XScream = (stateful: Stateful): void => {}
export const A_Look = (stateful: Stateful): void => {}
export const A_Chase = (stateful: Stateful): void => {}
export const A_FaceTarget = (stateful: Stateful): void => {}
export const A_PosAttack = (stateful: Stateful): void => {}
export const A_Scream = (stateful: Stateful): void => {}
export const A_SPosAttack = (stateful: Stateful): void => {}
export const A_VileChase = (stateful: Stateful): void => {}
export const A_VileStart = (stateful: Stateful): void => {}
export const A_VileTarget = (stateful: Stateful): void => {}
export const A_VileAttack = (stateful: Stateful): void => {}
export const A_StartFire = (stateful: Stateful): void => {}
export const A_Fire = (stateful: Stateful): void => {}
export const A_FireCrackle = (stateful: Stateful): void => {}
export const A_Tracer = (stateful: Stateful): void => {}
export const A_SkelWhoosh = (stateful: Stateful): void => {}
export const A_SkelFist = (stateful: Stateful): void => {}
export const A_SkelMissile = (stateful: Stateful): void => {}
export const A_FatRaise = (stateful: Stateful): void => {}
export const A_FatAttack1 = (stateful: Stateful): void => {}
export const A_FatAttack2 = (stateful: Stateful): void => {}
export const A_FatAttack3 = (stateful: Stateful): void => {}
export const A_BossDeath = (stateful: Stateful): void => {}
export const A_CPosAttack = (stateful: Stateful): void => {}
export const A_CPosRefire = (stateful: Stateful): void => {}
export const A_TroopAttack = (stateful: Stateful): void => {}
export const A_SargAttack = (stateful: Stateful): void => {}
export const A_HeadAttack = (stateful: Stateful): void => {}
export const A_BruisAttack = (stateful: Stateful): void => {}
export const A_SkullAttack = (stateful: Stateful): void => {}
export const A_Metal = (stateful: Stateful): void => {}
export const A_SpidRefire = (stateful: Stateful): void => {}
export const A_BabyMetal = (stateful: Stateful): void => {}
export const A_BspiAttack = (stateful: Stateful): void => {}
export const A_Hoof = (stateful: Stateful): void => {}
export const A_CyberAttack = (stateful: Stateful): void => {}
export const A_PainAttack = (stateful: Stateful): void => {}
export const A_PainDie = (stateful: Stateful): void => {}
export const A_KeenDie = (stateful: Stateful): void => {}
export const A_BrainPain = (stateful: Stateful): void => {}
export const A_BrainScream = (stateful: Stateful): void => {}
export const A_BrainDie = (stateful: Stateful): void => {}
export const A_BrainAwake = (stateful: Stateful): void => {}
export const A_BrainSpit = (stateful: Stateful): void => {}
export const A_SpawnSound = (stateful: Stateful): void => {}
export const A_SpawnFly = (stateful: Stateful): void => {}
export const A_BrainExplode = (stateful: Stateful): void => {}
